//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Validation.ValidationString", typeof(ValidationString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre compte n&apos;est pas encore activé. Pour continuer, vous devez d&apos;abord activer votre compte en cliquant sur le lien qui vous a été envoyé suite à votre inscription..
        /// </summary>
        public static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention, votre compte a fait l&apos;objet d&apos;un grand nombre de tentatives de connexion infructueuses. Pour préserver la sécurité de votre compte, eWorky l&apos;a temporairement bloqué. Pour le réactiver, contactez-nous..
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il semble que vous ayez oublié d&apos;attribuer une note !.
        /// </summary>
        public static string AlreadyRateThis {
            get {
                return ResourceManager.GetString("AlreadyRateThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur ne peut pas être null ou vide..
        /// </summary>
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez verifier vos critères..
        /// </summary>
        public static string CheckCriterias {
            get {
                return ResourceManager.GetString("CheckCriterias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La demande de création d&apos;utilisateur a été annulée. Vérifiez votre entrée et réessayez. Si le problème persiste, contactez votre administrateur système..
        /// </summary>
        public static string CreateUsernameFail {
            get {
                return ResourceManager.GetString("CreateUsernameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un lieu de travail avec le même nom et situé au même endroit existe déjà.
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file upload result.
        /// </summary>
        public static string EmptyFileUpload {
            get {
                return ResourceManager.GetString("EmptyFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur empeche la sauvegarde..
        /// </summary>
        public static string ErrorWhenSave {
            get {
                return ResourceManager.GetString("ErrorWhenSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write file to disk.
        /// </summary>
        public static string FailWriteToDisk {
            get {
                return ResourceManager.GetString("FailWriteToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too big.
        /// </summary>
        public static string FileTooBig {
            get {
                return ResourceManager.GetString("FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too small.
        /// </summary>
        public static string FileTooSmall {
            get {
                return ResourceManager.GetString("FileTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La réponse de récupération du mot de passe fournie n&apos;est pas valide. Vérifiez la valeur et réessayez..
        /// </summary>
        public static string GetBackPasswordMailNotValide {
            get {
                return ResourceManager.GetString("GetBackPasswordMailNotValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La question de récupération du mot de passe fournie n&apos;est pas valide. Vérifiez la valeur et réessayez..
        /// </summary>
        public static string GetBackPasswordQuestionNotValide {
            get {
                return ResourceManager.GetString("GetBackPasswordQuestionNotValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez indiquer au minimum une offre..
        /// </summary>
        public static string GiveMinADate {
            get {
                return ResourceManager.GetString("GiveMinADate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe fourni n&apos;est pas valide. Entrez une valeur de mot de passe valide..
        /// </summary>
        public static string GivenPasswordNotValide {
            get {
                return ResourceManager.GetString("GivenPasswordNotValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur inconnue s&apos;est produite. Vérifiez votre entrée et réessayez. Si le problème persiste, contactez votre administrateur système..
        /// </summary>
        public static string InknowError {
            get {
                return ResourceManager.GetString("InknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur non valide !.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse électronique ne correspond à aucun utilisateur..
        /// </summary>
        public static string MailDoNotMatch {
            get {
                return ResourceManager.GetString("MailDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse électronique entrée n&apos;est pas au bon format..
        /// </summary>
        public static string MailHaveNotGoodPattern {
            get {
                return ResourceManager.GetString("MailHaveNotGoodPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse électronique fournie n&apos;est pas valide. Vérifiez la valeur et réessayez..
        /// </summary>
        public static string MailNotValide {
            get {
                return ResourceManager.GetString("MailNotValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse électronique ou le mot de passe fourni est incorrect..
        /// </summary>
        public static string MailOrPasswordNotCorrect {
            get {
                return ResourceManager.GetString("MailOrPasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention, vous avez saisi un mot de passe de confirmation différent. Veuillez réessayer..
        /// </summary>
        public static string MatchPassword {
            get {
                return ResourceManager.GetString("MatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exceeds MAX_FILE_SIZE (HTML form directive).
        /// </summary>
        public static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit comporter moins de {1} caractères..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit comporter plus de {1} caractères..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit comporter entre {2} et {1} caractères..
        /// </summary>
        public static string MinMaxLength {
            get {
                return ResourceManager.GetString("MinMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez accepter les Conditions Générales d&apos;Utilisation pour vous inscrire sur eWorky..
        /// </summary>
        public static string MustAgreeCGU {
            get {
                return ResourceManager.GetString("MustAgreeCGU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File was uploaded.
        /// </summary>
        public static string NoFileUploaded {
            get {
                return ResourceManager.GetString("NoFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} ne correspond pas à une date valide..
        /// </summary>
        public static string NoValideDate {
            get {
                return ResourceManager.GetString("NoValideDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of files exceeded.
        /// </summary>
        public static string NumberFileExceeded {
            get {
                return ResourceManager.GetString("NumberFileExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was only partially uploaded.
        /// </summary>
        public static string PartialUpload {
            get {
                return ResourceManager.GetString("PartialUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe actuel est incorrect ou le nouveau mot de passe n&apos;est pas valide..
        /// </summary>
        public static string PasswordNotValide {
            get {
                return ResourceManager.GetString("PasswordNotValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre adresse électronique n&apos;est pas valide. Veuillez réessayer..
        /// </summary>
        public static string PatternEmail {
            get {
                return ResourceManager.GetString("PatternEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;1 Mo max.
        /// </summary>
        public static string PictureTooBig {
            get {
                return ResourceManager.GetString("PictureTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;Maximun&lt;br/&gt;Atteint.
        /// </summary>
        public static string PictureTooMuch {
            get {
                return ResourceManager.GetString("PictureTooMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;Trop petit.
        /// </summary>
        public static string PictureTooSmall {
            get {
                return ResourceManager.GetString("PictureTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;Mauvaise&lt;br/&gt;extention.
        /// </summary>
        public static string PictureWrongExtention {
            get {
                return ResourceManager.GetString("PictureWrongExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez sélectionner un profil..
        /// </summary>
        public static string PleaseSelectProfile {
            get {
                return ResourceManager.GetString("PleaseSelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être compris entre {1} et {2}..
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez saisir un(e) &quot;{0}&quot;..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fournisseur d&apos;authentification a retourné une erreur. Vérifiez votre entrée et réessayez. Si le problème persiste, contactez votre administrateur système..
        /// </summary>
        public static string ReturnErrorTryAgain {
            get {
                return ResourceManager.GetString("ReturnErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez choisir une valeur pour le champ &quot;{0}&quot;..
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a temporary folder.
        /// </summary>
        public static string TempFolderMissing {
            get {
                return ResourceManager.GetString("TempFolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; et &apos;{1}&apos; ne correspondent pas..
        /// </summary>
        public static string TheTwoNotMatch {
            get {
                return ResourceManager.GetString("TheTwoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filetype not allowed.
        /// </summary>
        public static string TypeNotAllowed {
            get {
                return ResourceManager.GetString("TypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded bytes exceed file size.
        /// </summary>
        public static string UploadedBytesExceedFileSize {
            get {
                return ResourceManager.GetString("UploadedBytesExceedFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exceeds upload_max_filesize (php.ini directive).
        /// </summary>
        public static string UploadMaxFileSize {
            get {
                return ResourceManager.GetString("UploadMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload stopped by extension.
        /// </summary>
        public static string UploadStopExtension {
            get {
                return ResourceManager.GetString("UploadStopExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisateur existe déjà. Entrez un nom d&apos;utilisateur différent..
        /// </summary>
        public static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il existe déjà un compte associé à cette adresse électronique. Veuillez vous connecter avec le compte existant ou saisir une adresse électronique différente..
        /// </summary>
        public static string UsernameExistForThisMail {
            get {
                return ResourceManager.GetString("UsernameExistForThisMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisateur fourni n&apos;est pas valide. Vérifiez la valeur et réessayez..
        /// </summary>
        public static string UsernameNotValide {
            get {
                return ResourceManager.GetString("UsernameNotValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les lettres vérification saisies sont incorrectes..
        /// </summary>
        public static string VerificationLettersWrong {
            get {
                return ResourceManager.GetString("VerificationLettersWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse web entrée n&apos;est pas au bon format..
        /// </summary>
        public static string WebsiteNotGoodPattern {
            get {
                return ResourceManager.GetString("WebsiteNotGoodPattern", resourceCulture);
            }
        }
    }
}
