//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Booking {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BookingString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookingString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Booking.BookingString", typeof(BookingString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achevée le .
        /// </summary>
        public static string Achieved {
            get {
                return ResourceManager.GetString("Achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to après-midi.
        /// </summary>
        public static string Afternoon {
            get {
                return ResourceManager.GetString("Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandé le.
        /// </summary>
        public static string Asked {
            get {
                return ResourceManager.GetString("Asked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de devis pour {0}.
        /// </summary>
        public static string AskingQuotation {
            get {
                return ResourceManager.GetString("AskingQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de devis.
        /// </summary>
        public static string AskQuotation {
            get {
                return ResourceManager.GetString("AskQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string BackToUrl {
            get {
                return ResourceManager.GetString("BackToUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez indiquer les date et heure de début et de fin de votre réservation..
        /// </summary>
        public static string BeginSpeech {
            get {
                return ResourceManager.GetString("BeginSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réservation.
        /// </summary>
        public static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La demande de réservation a été confirmée..
        /// </summary>
        public static string BookingAccepted {
            get {
                return ResourceManager.GetString("BookingAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre réservation ne peut pas débuter avant aujourd&apos;hui..
        /// </summary>
        public static string BookingBeforeToday {
            get {
                return ResourceManager.GetString("BookingBeforeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande de réservation a été annulée..
        /// </summary>
        public static string BookingCanceled {
            get {
                return ResourceManager.GetString("BookingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de la réservation.
        /// </summary>
        public static string BookingDetails {
            get {
                return ResourceManager.GetString("BookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remplir les champs pour réserver, un e-mail vous sera envoyé.
        /// </summary>
        public static string BookingIntro {
            get {
                return ResourceManager.GetString("BookingIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La demande de réservation a été refusée..
        /// </summary>
        public static string BookingRefused {
            get {
                return ResourceManager.GetString("BookingRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réserver.
        /// </summary>
        public static string BookIt {
            get {
                return ResourceManager.GetString("BookIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La réservation pour le lieu {0} à été payée !.
        /// </summary>
        public static string BookPaid {
            get {
                return ResourceManager.GetString("BookPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour effectuer une demande de réservation, remplissez les champs suivants..
        /// </summary>
        public static string BookSpeech {
            get {
                return ResourceManager.GetString("BookSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulée le .
        /// </summary>
        public static string CancelStatus {
            get {
                return ResourceManager.GetString("CancelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choisir un nombre de jours.
        /// </summary>
        public static string ChooseDay {
            get {
                return ResourceManager.GetString("ChooseDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choisir un nombre de demi-journées.
        /// </summary>
        public static string ChooseHalfDay {
            get {
                return ResourceManager.GetString("ChooseHalfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choisir un nombre d&apos;heures.
        /// </summary>
        public static string ChooseHours {
            get {
                return ResourceManager.GetString("ChooseHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choisir un nombre de mois.
        /// </summary>
        public static string ChooseMonth {
            get {
                return ResourceManager.GetString("ChooseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choisir un nombre de semaines.
        /// </summary>
        public static string ChooseWeek {
            get {
                return ResourceManager.GetString("ChooseWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choisir un nombre d&apos;années.
        /// </summary>
        public static string ChooseYear {
            get {
                return ResourceManager.GetString("ChooseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande de réservation a été correctement prise en compte. Le prix et la disponibilité vont être confirmés par le gérant..
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        public static string ConfirmIt {
            get {
                return ResourceManager.GetString("ConfirmIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact établi le .
        /// </summary>
        public static string ContactStatus {
            get {
                return ResourceManager.GetString("ContactStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client(e).
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de fin de votre réservation doit être postérieure à la date de début..
        /// </summary>
        public static string EndBookingBeforeStart {
            get {
                return ResourceManager.GetString("EndBookingBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous serez contacté dans les meilleurs délais par le gérant du lieu..
        /// </summary>
        public static string EndQuotationSpeech {
            get {
                return ResourceManager.GetString("EndQuotationSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La disponibilité et le prix pour cette demande de réservation vous seront confirmés par le gérant dans votre Espace utilisateur. Une fois confirmée, vous pourrez alors régler en ligne votre réservation..
        /// </summary>
        public static string EndSpeech {
            get {
                return ResourceManager.GetString("EndSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prendre en charge.
        /// </summary>
        public static string HandleIt {
            get {
                return ResourceManager.GetString("HandleIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a accepté la demande de réservation pour {1}.
        /// </summary>
        public static string HasAcceptBooking {
            get {
                return ResourceManager.GetString("HasAcceptBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a fait une demande de réservation pour {1}.
        /// </summary>
        public static string HasAskBooking {
            get {
                return ResourceManager.GetString("HasAskBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a fait une demande de devis pour {1}.
        /// </summary>
        public static string HasAskQuotation {
            get {
                return ResourceManager.GetString("HasAskQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a annulé la demande de réservation pour {1}.
        /// </summary>
        public static string HasCancelBooking {
            get {
                return ResourceManager.GetString("HasCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a annulé la demande de devis pour {1}.
        /// </summary>
        public static string HasCancelQuotation {
            get {
                return ResourceManager.GetString("HasCancelQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a payé la demande de réservation pour {1}.
        /// </summary>
        public static string HasPaidBooking {
            get {
                return ResourceManager.GetString("HasPaidBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a payé la demande de devis pour {1}.
        /// </summary>
        public static string HasPaidQuotation {
            get {
                return ResourceManager.GetString("HasPaidQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a refusé la demande de réservation pour {1}.
        /// </summary>
        public static string HasRefuseBooking {
            get {
                return ResourceManager.GetString("HasRefuseBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a refusé la demande de devis pour {1}.
        /// </summary>
        public static string HasRefuseQuotation {
            get {
                return ResourceManager.GetString("HasRefuseQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment ça marche.
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous indiquez les détails de votre réservation.
        /// </summary>
        public static string HowItWorks1 {
            get {
                return ResourceManager.GetString("HowItWorks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande sera alors immédiatement transmise au gérant.
        /// </summary>
        public static string HowItWorks2 {
            get {
                return ResourceManager.GetString("HowItWorks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous recevrez ainsi dans votre espace utilisateur une confirmation du prix et des disponibilités.
        /// </summary>
        public static string HowItWorks3 {
            get {
                return ResourceManager.GetString("HowItWorks3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pourrez alors régler en ligne votre réservation.
        /// </summary>
        public static string HowItWorks4 {
            get {
                return ResourceManager.GetString("HowItWorks4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieu.
        /// </summary>
        public static string Localisation {
            get {
                return ResourceManager.GetString("Localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message au gérant.
        /// </summary>
        public static string MessageToOwner {
            get {
                return ResourceManager.GetString("MessageToOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matin.
        /// </summary>
        public static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez indiquer une quantité non nulle.
        /// </summary>
        public static string NotNullQuantity {
            get {
                return ResourceManager.GetString("NotNullQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offre.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payé le .
        /// </summary>
        public static string PaidStatus {
            get {
                return ResourceManager.GetString("PaidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Régler.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le payment n&apos;a pas été pris en compte !.
        /// </summary>
        public static string PayFail {
            get {
                return ResourceManager.GetString("PayFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur emepeche le paymenent, veuillez nous contacter à support@eworky.com..
        /// </summary>
        public static string PaymentError {
            get {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de devis.
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de devis annulé le .
        /// </summary>
        public static string QuotationCancel {
            get {
                return ResourceManager.GetString("QuotationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande de devis a été annulée..
        /// </summary>
        public static string QuotationCanceled {
            get {
                return ResourceManager.GetString("QuotationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande de devis a correctement été prise en compte..
        /// </summary>
        public static string QuotationConfirmed {
            get {
                return ResourceManager.GetString("QuotationConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de devis refusée le .
        /// </summary>
        public static string QuotationRefuse {
            get {
                return ResourceManager.GetString("QuotationRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La demande de devis a été refusée..
        /// </summary>
        public static string QuotationRefused {
            get {
                return ResourceManager.GetString("QuotationRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour effectuer une demande de devis, remplissez les champs suivants..
        /// </summary>
        public static string QuotationSpeech {
            get {
                return ResourceManager.GetString("QuotationSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuser.
        /// </summary>
        public static string RefuseIt {
            get {
                return ResourceManager.GetString("RefuseIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusée le .
        /// </summary>
        public static string RefuseStatus {
            get {
                return ResourceManager.GetString("RefuseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir la fiche du client.
        /// </summary>
        public static string SeeCustomerSheet {
            get {
                return ResourceManager.GetString("SeeCustomerSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir la fiche du lieu.
        /// </summary>
        public static string SeeLocSheet {
            get {
                return ResourceManager.GetString("SeeLocSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        public static string Surface {
            get {
                return ResourceManager.GetString("Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jusqu&apos;au.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider la demande de devis.
        /// </summary>
        public static string ValidateQuotation {
            get {
                return ResourceManager.GetString("ValidateQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de confirmation.
        /// </summary>
        public static string WaitingConfirm {
            get {
                return ResourceManager.GetString("WaitingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de payment.
        /// </summary>
        public static string WaitingForPayement {
            get {
                return ResourceManager.GetString("WaitingForPayement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de réglement.
        /// </summary>
        public static string WaitingPayment {
            get {
                return ResourceManager.GetString("WaitingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de prise en charge.
        /// </summary>
        public static string WaitingStatus {
            get {
                return ResourceManager.GetString("WaitingStatus", resourceCulture);
            }
        }
    }
}
