//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.237
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Admin {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminString() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Admin.AdminString", typeof(AdminString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur absent.
        /// </summary>
        public static string AbsentUser {
            get {
                return ResourceManager.GetString("AbsentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déjà inscrit.
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour a la liste.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer la suppression : .
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez confirmer la suppression de l&apos;article :.
        /// </summary>
        public static string ConfirmDeletePress {
            get {
                return ResourceManager.GetString("ConfirmDeletePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez confirmer la suppression de l&apos;utilisateur :.
        /// </summary>
        public static string ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez confirmer la suppression d&apos;une personne de la page d&apos;accueil :.
        /// </summary>
        public static string ConfirmDeleteWelcome {
            get {
                return ResourceManager.GetString("ConfirmDeleteWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un nouvel article.
        /// </summary>
        public static string CreateNewPress {
            get {
                return ResourceManager.GetString("CreateNewPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un nouveau profil.
        /// </summary>
        public static string CreateNewWelcomePeople {
            get {
                return ResourceManager.GetString("CreateNewWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer profil page d&apos;accueil.
        /// </summary>
        public static string CreateWelcomePeople {
            get {
                return ResourceManager.GetString("CreateWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détail d&apos;un article.
        /// </summary>
        public static string DetailPress {
            get {
                return ResourceManager.GetString("DetailPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détail d&apos;un personne de la page d&apos;accueil.
        /// </summary>
        public static string DetailWelcomePeople {
            get {
                return ResourceManager.GetString("DetailWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer un article.
        /// </summary>
        public static string EditPress {
            get {
                return ResourceManager.GetString("EditPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer une personne de la page d&apos;accueil.
        /// </summary>
        public static string EditWelcomePeople {
            get {
                return ResourceManager.GetString("EditWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse électronique.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des réservations.
        /// </summary>
        public static string IndexBooking {
            get {
                return ResourceManager.GetString("IndexBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des articles.
        /// </summary>
        public static string IndexPress {
            get {
                return ResourceManager.GetString("IndexPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des entrepreneurs stars.
        /// </summary>
        public static string IndexWelcomePeople {
            get {
                return ResourceManager.GetString("IndexWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Article Inexistant.
        /// </summary>
        public static string InexistingPress {
            get {
                return ResourceManager.GetString("InexistingPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscrit(e).
        /// </summary>
        public static string IsRegistered {
            get {
                return ResourceManager.GetString("IsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Métier.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localisation.
        /// </summary>
        public static string Localisation {
            get {
                return ResourceManager.GetString("Localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo du lieu.
        /// </summary>
        public static string LocalisationPicture {
            get {
                return ResourceManager.GetString("LocalisationPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion de lieux de travail.
        /// </summary>
        public static string LocalisationsAdmin {
            get {
                return ResourceManager.GetString("LocalisationsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrateur.
        /// </summary>
        public static string ManagerRole {
            get {
                return ResourceManager.GetString("ManagerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous sommes désolés, le lieu de travail séléctionné n&apos;existe pas ou a été effacé..
        /// </summary>
        public static string PlaceDeletedSorry {
            get {
                return ResourceManager.GetString("PlaceDeletedSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point(s).
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous sommes désolés, l&apos;article séléctionné n&apos;existe pas ou a été effacé..
        /// </summary>
        public static string PressDeleted {
            get {
                return ResourceManager.GetString("PressDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Article non trouvé.
        /// </summary>
        public static string PressNotFound {
            get {
                return ResourceManager.GetString("PressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à envoyer.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi e-mail.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la une.
        /// </summary>
        public static string TheTop {
            get {
                return ResourceManager.GetString("TheTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour des rôles.
        /// </summary>
        public static string UpdateRole {
            get {
                return ResourceManager.GetString("UpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des utilisateurs.
        /// </summary>
        public static string UserAdmin {
            get {
                return ResourceManager.GetString("UserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration des Utilisateurs.
        /// </summary>
        public static string UserAdministration {
            get {
                return ResourceManager.GetString("UserAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à validation d&apos;envoi.
        /// </summary>
        public static string ValidationSend {
            get {
                return ResourceManager.GetString("ValidationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion de la bêta privée.
        /// </summary>
        public static string VisitorAdministration {
            get {
                return ResourceManager.GetString("VisitorAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En attente d&apos;inscription.
        /// </summary>
        public static string WaitInscription {
            get {
                return ResourceManager.GetString("WaitInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu de travail non trouvé.
        /// </summary>
        public static string WorkspaceNotFound {
            get {
                return ResourceManager.GetString("WorkspaceNotFound", resourceCulture);
            }
        }
    }
}
