//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Admin.AdminString", typeof(AdminString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration des Locations.
        /// </summary>
        public static string AdminRental {
            get {
                return ResourceManager.GetString("AdminRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espace administrateur.
        /// </summary>
        public static string AdminSpace {
            get {
                return ResourceManager.GetString("AdminSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Attention : Les lieux de travail suivant n&apos;ont pas été ajoutés car ils existaient déjà dans la base de donnée &lt;br /&gt;&lt;/b&gt; {0}.
        /// </summary>
        public static string AlreadyAdded {
            get {
                return ResourceManager.GetString("AlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déjà inscrit.
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour a la liste.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la suppression : .
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmer la suppression de l&apos;article :.
        /// </summary>
        public static string ConfirmDeletePress {
            get {
                return ResourceManager.GetString("ConfirmDeletePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmer la suppression de l&apos;annonce :.
        /// </summary>
        public static string ConfirmDeleteRental {
            get {
                return ResourceManager.GetString("ConfirmDeleteRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmer la suppression de l&apos;utilisateur :.
        /// </summary>
        public static string ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmer la suppression d&apos;une personne de la page d&apos;accueil :.
        /// </summary>
        public static string ConfirmDeleteWelcome {
            get {
                return ResourceManager.GetString("ConfirmDeleteWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un nouvel article.
        /// </summary>
        public static string CreateNewPress {
            get {
                return ResourceManager.GetString("CreateNewPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un nouveau profil.
        /// </summary>
        public static string CreateNewWelcomePeople {
            get {
                return ResourceManager.GetString("CreateNewWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une annonce.
        /// </summary>
        public static string CreateRental {
            get {
                return ResourceManager.GetString("CreateRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer profil page d&apos;accueil.
        /// </summary>
        public static string CreateWelcomePeople {
            get {
                return ResourceManager.GetString("CreateWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail d&apos;un article.
        /// </summary>
        public static string DetailPress {
            get {
                return ResourceManager.GetString("DetailPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail d&apos;un personne de la page d&apos;accueil.
        /// </summary>
        public static string DetailWelcomePeople {
            get {
                return ResourceManager.GetString("DetailWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer un article.
        /// </summary>
        public static string EditPress {
            get {
                return ResourceManager.GetString("EditPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer une personne de la page d&apos;accueil.
        /// </summary>
        public static string EditWelcomePeople {
            get {
                return ResourceManager.GetString("EditWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse électronique eWorker.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse électronique.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom exact du lieu.
        /// </summary>
        public static string ExactLoc {
            get {
                return ResourceManager.GetString("ExactLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier comporte une ligne d&apos;en-tête.
        /// </summary>
        public static string FileGotHeader {
            get {
                return ResourceManager.GetString("FileGotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des réservations.
        /// </summary>
        public static string IndexBooking {
            get {
                return ResourceManager.GetString("IndexBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des articles.
        /// </summary>
        public static string IndexPress {
            get {
                return ResourceManager.GetString("IndexPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des devis.
        /// </summary>
        public static string IndexQuotation {
            get {
                return ResourceManager.GetString("IndexQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des entrepreneurs stars.
        /// </summary>
        public static string IndexWelcomePeople {
            get {
                return ResourceManager.GetString("IndexWelcomePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Inexistant.
        /// </summary>
        public static string InexistingPress {
            get {
                return ResourceManager.GetString("InexistingPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrit(e).
        /// </summary>
        public static string IsRegistered {
            get {
                return ResourceManager.GetString("IsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des articles répertoriés sur eWorky :.
        /// </summary>
        public static string ListPress {
            get {
                return ResourceManager.GetString("ListPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation.
        /// </summary>
        public static string Localisation {
            get {
                return ResourceManager.GetString("Localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo du lieu.
        /// </summary>
        public static string LocalisationPicture {
            get {
                return ResourceManager.GetString("LocalisationPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de lieux de travail.
        /// </summary>
        public static string LocalisationsAdmin {
            get {
                return ResourceManager.GetString("LocalisationsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;e-mail a été envoyé avec succès..
        /// </summary>
        public static string MailHaveBeenSent {
            get {
                return ResourceManager.GetString("MailHaveBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrateur.
        /// </summary>
        public static string ManagerRole {
            get {
                return ResourceManager.GetString("ManagerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online/Offline.
        /// </summary>
        public static string OnOffLine {
            get {
                return ResourceManager.GetString("OnOffLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérant.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous sommes désolés, le lieu de travail séléctionné n&apos;existe pas ou a été effacé..
        /// </summary>
        public static string PlaceDeletedSorry {
            get {
                return ResourceManager.GetString("PlaceDeletedSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point(s).
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous sommes désolés, l&apos;article séléctionné n&apos;existe pas ou a été effacé..
        /// </summary>
        public static string PressDeleted {
            get {
                return ResourceManager.GetString("PressDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;article de presse a été créé..
        /// </summary>
        public static string PressHaveBeenCreate {
            get {
                return ResourceManager.GetString("PressHaveBeenCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;article de presse a été supprimé..
        /// </summary>
        public static string PressHaveBeenDel {
            get {
                return ResourceManager.GetString("PressHaveBeenDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;article de presse a été édité..
        /// </summary>
        public static string PressHaveBeenEdit {
            get {
                return ResourceManager.GetString("PressHaveBeenEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article non trouvé..
        /// </summary>
        public static string PressNotFound {
            get {
                return ResourceManager.GetString("PressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Rentals {
            get {
                return ResourceManager.GetString("Rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les rôles ont été changés..
        /// </summary>
        public static string RoleHaveBeenSet {
            get {
                return ResourceManager.GetString("RoleHaveBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to envoyer.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoi e-mail.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la une.
        /// </summary>
        public static string TheTop {
            get {
                return ResourceManager.GetString("TheTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocker.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour des rôles.
        /// </summary>
        public static string UpdateRole {
            get {
                return ResourceManager.GetString("UpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des utilisateurs.
        /// </summary>
        public static string UserAdmin {
            get {
                return ResourceManager.GetString("UserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration des Utilisateurs.
        /// </summary>
        public static string UserAdministration {
            get {
                return ResourceManager.GetString("UserAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur a été supprimé..
        /// </summary>
        public static string UserHaveBeenDel {
            get {
                return ResourceManager.GetString("UserHaveBeenDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur non trouvé..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validation d&apos;envoi.
        /// </summary>
        public static string ValidationSend {
            get {
                return ResourceManager.GetString("ValidationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de la bêta privée.
        /// </summary>
        public static string VisitorAdministration {
            get {
                return ResourceManager.GetString("VisitorAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiteur non trouvé..
        /// </summary>
        public static string VisitorNotFound {
            get {
                return ResourceManager.GetString("VisitorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente d&apos;inscription.
        /// </summary>
        public static string WaitInscription {
            get {
                return ResourceManager.GetString("WaitInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entrepreneur star a été créé..
        /// </summary>
        public static string WelcomePeopleHaveBeenCreate {
            get {
                return ResourceManager.GetString("WelcomePeopleHaveBeenCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entrepreneur star a été supprimé..
        /// </summary>
        public static string WelcomePeopleHaveBeenDel {
            get {
                return ResourceManager.GetString("WelcomePeopleHaveBeenDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entrepreneur star a été édité..
        /// </summary>
        public static string WelcomePeopleHaveBeenEdit {
            get {
                return ResourceManager.GetString("WelcomePeopleHaveBeenEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entrepreneur star non trouvé..
        /// </summary>
        public static string WelcomePeopleNotFound {
            get {
                return ResourceManager.GetString("WelcomePeopleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieu de travail non trouvé..
        /// </summary>
        public static string WorkspaceNotFound {
            get {
                return ResourceManager.GetString("WorkspaceNotFound", resourceCulture);
            }
        }
    }
}
