//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Admin.StatString", typeof(StatString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biblio / Musée.
        /// </summary>
        public static string Biblio {
            get {
                return ResourceManager.GetString("Biblio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre d&apos;aff..
        /// </summary>
        public static string BuisnessCenter {
            get {
                return ResourceManager.GetString("BuisnessCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Café / Restau.
        /// </summary>
        public static string CoffeeResto {
            get {
                return ResourceManager.GetString("CoffeeResto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esp. cowork..
        /// </summary>
        public static string CoworkingSpace {
            get {
                return ResourceManager.GetString("CoworkingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date / Heure.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorker.
        /// </summary>
        public static string EworkerName {
            get {
                return ResourceManager.GetString("EworkerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorkers.
        /// </summary>
        public static string Eworkers {
            get {
                return ResourceManager.GetString("Eworkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôtel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernières créations.
        /// </summary>
        public static string LastCreate {
            get {
                return ResourceManager.GetString("LastCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernières modifications.
        /// </summary>
        public static string LastModif {
            get {
                return ResourceManager.GetString("LastModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total par pays.
        /// </summary>
        public static string NbByCountry {
            get {
                return ResourceManager.GetString("NbByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du lieu.
        /// </summary>
        public static string PlaceName {
            get {
                return ResourceManager.GetString("PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieu privé.
        /// </summary>
        public static string PrivateArea {
            get {
                return ResourceManager.GetString("PrivateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPN / Cyber.
        /// </summary>
        public static string PublicSpace {
            get {
                return ResourceManager.GetString("PublicSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiques.
        /// </summary>
        public static string StatTitle {
            get {
                return ResourceManager.GetString("StatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécentre.
        /// </summary>
        public static string Telecentre {
            get {
                return ResourceManager.GetString("Telecentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esp. voyag..
        /// </summary>
        public static string TravelerSpace {
            get {
                return ResourceManager.GetString("TravelerSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot wifi.
        /// </summary>
        public static string Wifi {
            get {
                return ResourceManager.GetString("Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôtel d&apos;ent..
        /// </summary>
        public static string WorkingHotel {
            get {
                return ResourceManager.GetString("WorkingHotel", resourceCulture);
            }
        }
    }
}
