// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.488
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Worki.SpecFlow.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Ajout")]
    public partial class AjoutFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AjoutFeature.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Ajout", "In order to search a working place\r\nAs a user\r\nI want to be able to view the list" +
                    " of localisations", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11 Créer une fiche de lieu Gratuit")]
        [NUnit.Framework.CategoryAttribute("Ajout")]
        public virtual void _11CreerUneFicheDeLieuGratuit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11 Créer une fiche de lieu Gratuit", new string[] {
                        "Ajout"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("Je me connecte à eWorky");
#line 9
  testRunner.And("Je vais dans la page d\'ajout de lieux gratuits");
#line 10
  testRunner.And("Je remplis les champs");
#line 11
 testRunner.When("Je clique sur Envoyer");
#line 12
 testRunner.Then("Je dois retrouver les infos");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12 Ajout de lieu deja present")]
        [NUnit.Framework.CategoryAttribute("Ajout")]
        public virtual void _12AjoutDeLieuDejaPresent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12 Ajout de lieu deja present", new string[] {
                        "Ajout"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("Je me connecte à eWorky");
#line 17
  testRunner.And("Je vais dans la page d\'ajout");
#line 18
  testRunner.And("Je remplis lieux deja rentré");
#line 19
 testRunner.When("Je clique sur Envoyer");
#line 20
 testRunner.Then("Il doit y avoir des messages d\'erreur");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13 Editer une fiche de lieu Gratuit")]
        [NUnit.Framework.CategoryAttribute("Ajout")]
        public virtual void _13EditerUneFicheDeLieuGratuit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13 Editer une fiche de lieu Gratuit", new string[] {
                        "Ajout"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("Je me connecte à eWorky");
#line 25
  testRunner.And("Je vais dans la page admin");
#line 26
  testRunner.And("Je clique sur editer");
#line 27
 testRunner.When("Je change les champs");
#line 28
  testRunner.And("Je clique sur Envoyer");
#line 29
 testRunner.Then("Je dois avoir retrouver les infos modifiées");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14 Supprimer une fiche de lieu Gratuit")]
        [NUnit.Framework.CategoryAttribute("Ajout")]
        public virtual void _14SupprimerUneFicheDeLieuGratuit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14 Supprimer une fiche de lieu Gratuit", new string[] {
                        "Ajout"});
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("Je me connecte à eWorky");
#line 34
  testRunner.And("Je vais dans la page admin");
#line 35
 testRunner.When("Je clique sur Supprimer");
#line 36
 testRunner.Then("La fiche de lieu est supprimée");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Créer une fiche de lieu Payant")]
        [NUnit.Framework.CategoryAttribute("Ajout")]
        public virtual void CreerUneFicheDeLieuPayant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Créer une fiche de lieu Payant", new string[] {
                        "Ajout"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given("Je me connecte à eWorky");
#line 41
  testRunner.And("Je vais dans la page d\'ajout de lieux payant");
#line 42
  testRunner.And("Je remplis les champs 2");
#line 43
 testRunner.When("Je clique sur Envoyer");
#line 44
 testRunner.Then("Je dois retrouver les infos 2");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Editer une fiche de lieu Payant")]
        [NUnit.Framework.CategoryAttribute("Ajout")]
        public virtual void EditerUneFicheDeLieuPayant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Editer une fiche de lieu Payant", new string[] {
                        "Ajout"});
#line 47
this.ScenarioSetup(scenarioInfo);
#line 48
 testRunner.Given("Je me connecte à eWorky");
#line 49
  testRunner.And("Je vais dans la page admin");
#line 50
  testRunner.And("Je clique sur editer");
#line 51
 testRunner.When("Je change les champs 2");
#line 52
  testRunner.And("Je clique sur Envoyer");
#line 53
 testRunner.Then("Je dois avoir retrouver les infos modifiées 2");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Supprimer une fiche de lieu Payant")]
        [NUnit.Framework.CategoryAttribute("Ajout")]
        public virtual void SupprimerUneFicheDeLieuPayant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Supprimer une fiche de lieu Payant", new string[] {
                        "Ajout"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("Je me connecte à eWorky");
#line 58
  testRunner.And("Je vais dans la page admin");
#line 59
 testRunner.When("Je clique sur Supprimer");
#line 60
 testRunner.Then("La fiche de lieu est supprimée");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ajout Erreur")]
        [NUnit.Framework.CategoryAttribute("Ajout")]
        public virtual void AjoutErreur()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ajout Erreur", new string[] {
                        "Ajout"});
#line 63
this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.Given("Je me connecte à eWorky");
#line 65
  testRunner.And("Je vais dans la page d\'ajout");
#line 66
 testRunner.When("Je clique sur Envoyer");
#line 67
 testRunner.Then("Il doit y avoir des messages d\'erreur");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ajout mauvais pattern")]
        [NUnit.Framework.CategoryAttribute("Ajout")]
        public virtual void AjoutMauvaisPattern()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ajout mauvais pattern", new string[] {
                        "Ajout"});
#line 70
this.ScenarioSetup(scenarioInfo);
#line 71
 testRunner.Given("Je me connecte à eWorky");
#line 72
  testRunner.And("Je vais dans la page d\'ajout");
#line 73
  testRunner.And("Je remplis mal le champs Email");
#line 74
  testRunner.And("je remplis mal les horaires");
#line 75
 testRunner.When("Je clique sur Envoyer");
#line 76
 testRunner.Then("Il doit y avoir des messages d\'erreur");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
