// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace WorkiSpecFlow.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Vérif Page")]
    public partial class VerifPageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FooterFeature.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Vérif Page", "In order to search a working place\r\nAs a user\r\nI want to be able to view the list" +
                    " of localisations", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Mentions légale")]
        [NUnit.Framework.CategoryAttribute("Footer")]
        public virtual void MentionsLegale()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mentions légale", new string[] {
                        "Footer"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("Je vais dans la page d\'acceuil");
#line 9
 testRunner.When("Je vais dans la page mention légal");
#line 10
 testRunner.Then("Je dois avoir la page mention légal");
#line 11
  testRunner.And("Text présent sur la page: Omnicentre SAS");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Jobs")]
        [NUnit.Framework.CategoryAttribute("Footer")]
        public virtual void Jobs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Jobs", new string[] {
                        "Footer"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("Je vais dans la page d\'acceuil");
#line 16
 testRunner.When("Je vais dans la page de jobs");
#line 17
 testRunner.Then("Je dois avoir la page jobs");
#line 18
  testRunner.And("Text présent sur la page: L’esprit eWorky");
#line 19
  testRunner.And("Text présent sur la page: eWorky recherche des développeurs");
#line 20
  testRunner.And("Text présent sur la page: stagiaire en communication");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Presse")]
        [NUnit.Framework.CategoryAttribute("Footer")]
        public virtual void Presse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Presse", new string[] {
                        "Footer"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("Je vais dans la page d\'acceuil");
#line 26
 testRunner.When("Je vais dans la page presse");
#line 27
 testRunner.Then("Je dois avoir la page presse");
#line 28
  testRunner.And("Text présent sur la page: Vous êtes journaliste");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CGU")]
        [NUnit.Framework.CategoryAttribute("Footer")]
        public virtual void CGU()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CGU", new string[] {
                        "Footer"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("Je vais dans la page d\'acceuil");
#line 33
 testRunner.When("Je vais dans la page CGU");
#line 34
 testRunner.Then("Je dois avoir la page CGU");
#line 35
  testRunner.And("Text présent sur la page: Informations sur le fournisseur");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("FAQ")]
        [NUnit.Framework.CategoryAttribute("Footer")]
        public virtual void FAQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("FAQ", new string[] {
                        "Footer"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
 testRunner.Given("Je vais dans la page d\'acceuil");
#line 40
 testRunner.When("Je vais dans la page FAQ");
#line 41
 testRunner.Then("Je dois avoir la page FAQ");
#line 42
  testRunner.And("Text présent sur la page: A quoi sert eWorky ?");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Qui sommes nous")]
        [NUnit.Framework.CategoryAttribute("Footer")]
        public virtual void QuiSommesNous()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Qui sommes nous", new string[] {
                        "Footer"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.Given("Je vais dans la page d\'acceuil");
#line 47
 testRunner.When("Je vais dans la page Qui sommes nous");
#line 48
 testRunner.Then("Je dois avoir la page Qui sommes nous");
#line 49
  testRunner.And("Text présent sur la page: Supélec ou de Centrale Lyon");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Contact")]
        [NUnit.Framework.CategoryAttribute("Footer")]
        public virtual void Contact()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Contact", new string[] {
                        "Footer"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given("Je vais dans la page d\'acceuil");
#line 54
 testRunner.When("Je vais dans la page Contact");
#line 55
 testRunner.Then("Je dois avoir la page Contact");
#line 56
  testRunner.And("Text présent sur la page: Message");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
