// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Worki.SpecFlow.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Recherche Lieu")]
    public partial class RechercheLieuFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SearchFeature.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Recherche Lieu", "In order to search a working place\r\nAs a user\r\nI want to be able to view the list" +
                    " of localisations", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Recherche Simple")]
        [NUnit.Framework.CategoryAttribute("search")]
        public virtual void RechercheSimple()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recherche Simple", new string[] {
                        "search"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("Je vais dans la page Recherche");
#line 9
  testRunner.And("Je tappe Paris dans la zone de recherche");
#line 10
 testRunner.When("Je clique sur rechercher");
#line 11
 testRunner.Then("Il doit y avoir plus de 0 resultats");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Recherche Detailer")]
        [NUnit.Framework.CategoryAttribute("search")]
        public virtual void RechercheDetailer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recherche Detailer", new string[] {
                        "search"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("Je vais dans la page Recherche");
#line 16
  testRunner.And("Je tappe Paris dans la zone de recherche");
#line 17
  testRunner.And("Je coche la checkbox prise de courant");
#line 18
  testRunner.And("Je coche l\'equipement restaurant");
#line 19
  testRunner.And("Je selectionne Salon d\'affaire");
#line 20
 testRunner.When("Je clique sur rechercher");
#line 21
 testRunner.Then("Il doit y avoir plus de 1 resultats");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Recherche Erreur")]
        [NUnit.Framework.CategoryAttribute("search")]
        public virtual void RechercheErreur()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recherche Erreur", new string[] {
                        "search"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("Je vais dans la page Recherche");
#line 26
 testRunner.When("Je clique sur rechercher");
#line 27
 testRunner.Then("Je dois avoir un message d\'erreur");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Description Etudiant")]
        [NUnit.Framework.CategoryAttribute("search")]
        public virtual void DescriptionEtudiant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Description Etudiant", new string[] {
                        "search"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("Je vais dans la page Recherche");
#line 33
 testRunner.When("Je clique sur Etudiant");
#line 34
 testRunner.Then("Je dois avoir la description Etudiant");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Description Nomade")]
        [NUnit.Framework.CategoryAttribute("search")]
        public virtual void DescriptionNomade()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Description Nomade", new string[] {
                        "search"});
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("Je vais dans la page Recherche");
#line 39
 testRunner.When("Je clique sur Nomade");
#line 40
 testRunner.Then("Je dois avoir la description Nomade");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Description Teletravailleur")]
        [NUnit.Framework.CategoryAttribute("search")]
        public virtual void DescriptionTeletravailleur()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Description Teletravailleur", new string[] {
                        "search"});
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
 testRunner.Given("Je vais dans la page Recherche");
#line 45
 testRunner.When("Je clique sur Teletravailleur");
#line 46
 testRunner.Then("Je dois avoir la description Teletravailleur");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Description Entrepreneur")]
        [NUnit.Framework.CategoryAttribute("search")]
        public virtual void DescriptionEntrepreneur()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Description Entrepreneur", new string[] {
                        "search"});
#line 49
this.ScenarioSetup(scenarioInfo);
#line 50
 testRunner.Given("Je vais dans la page Recherche");
#line 51
 testRunner.When("Je clique sur Entrepreneur");
#line 52
 testRunner.Then("Je dois avoir la description Entrepreneur");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Description GrandCompte")]
        [NUnit.Framework.CategoryAttribute("search")]
        public virtual void DescriptionGrandCompte()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Description GrandCompte", new string[] {
                        "search"});
#line 55
this.ScenarioSetup(scenarioInfo);
#line 56
 testRunner.Given("Je vais dans la page Recherche");
#line 57
 testRunner.When("Je clique sur GrandCompte");
#line 58
 testRunner.Then("Je dois avoir la description GrandCompte");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Description Indépendant")]
        [NUnit.Framework.CategoryAttribute("search")]
        public virtual void DescriptionIndependant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Description Indépendant", new string[] {
                        "search"});
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("Je vais dans la page Recherche");
#line 63
 testRunner.When("Je clique sur Indépendant");
#line 64
 testRunner.Then("Je dois avoir la description Indépendant");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
