//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.237
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeString() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Home.HomeString", typeof(HomeString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les trois ingénieurs de Supélec ou de Centrale Lyon, presque tous déjà entrepreneurs (Greenworking), on avait régulièrement besoin d’accéder à un wifi, de louer une salle de réunion ou même une salle de formation..
        /// </summary>
        public static string AllSupelecNeedWifi {
            get {
                return ResourceManager.GetString("AllSupelecNeedWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un besoin.
        /// </summary>
        public static string ANeed {
            get {
                return ResourceManager.GetString("ANeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une équipe.
        /// </summary>
        public static string ATeam {
            get {
                return ResourceManager.GetString("ATeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à eWorky, avec ses jeux et ses lieux de travail insolites, est décidément le meilleur endroit pour travailler !.
        /// </summary>
        public static string BestPlaceToWork {
            get {
                return ResourceManager.GetString("BestPlaceToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le meilleur endroit pour travailler.
        /// </summary>
        public static string BestWorkspace {
            get {
                return ResourceManager.GetString("BestWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contactez-nous.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On a donc créé un site pour partager entre amis des bons plans en matière de lieux de travail. Cela nous a bien servi..
        /// </summary>
        public static string CreateTheWebSite {
            get {
                return ResourceManager.GetString("CreateTheWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le meilleur endroit pour travailler. Nomades, indépendants, télétravailleurs, proposez et trouvez le lieu de travail de vos rêves..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profiter..
        /// </summary>
        public static string Enjoy {
            get {
                return ResourceManager.GetString("Enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à eWorky est le premier portail français permettant à quiconque de trouver le lieu de travail qui lui convient là où il en a besoin. Et ce qu&apos;il s&apos;agisse d&apos;un restaurant équipé du wifi, d&apos;une salle de réunion de grand hôtel ou d&apos;un bureau en centre d’affaires..
        /// </summary>
        public static string EWorkyCouldFindWorkplace {
            get {
                return ResourceManager.GetString("EWorkyCouldFindWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ex : Pau, Oise, rue Rivoli Paris, 92200, ....
        /// </summary>
        public static string ExampleLocation {
            get {
                return ResourceManager.GetString("ExampleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trouver..
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trouver le lieu de travail de vos rêves.
        /// </summary>
        public static string FindDreamWorkspace {
            get {
                return ResourceManager.GetString("FindDreamWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Du plaisir.
        /// </summary>
        public static string Fun {
            get {
                return ResourceManager.GetString("Fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en fonction de critères avancés, noter, commenter.
        /// </summary>
        public static string GradeComment {
            get {
                return ResourceManager.GetString("GradeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En général on parvenait à en trouver par le bouche à oreille, mais il manquait quelque chose pour gagner du temps et obtenir les meilleures informations : une plate-forme collaborative de recherche de lieu de travail..
        /// </summary>
        public static string HowCameTheIdea {
            get {
                return ResourceManager.GetString("HowCameTheIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mentions légales.
        /// </summary>
        public static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce site web est édité par :&lt;br /&gt;
        ///        Omnicentre SAS&lt;br /&gt;
        ///        Société par actions simplifiée au capital de 10 000 € - RCS NANTERRE 529 309 668&lt;br /&gt;
        ///        Siège social : 30 rue des poissonniers, 92200 Neuilly-sur-Seine&lt;br /&gt;
        ///        &lt;br /&gt;
        ///        Contact :&lt;br /&gt;
        ///        {0}&lt;br /&gt;
        ///        &lt;br /&gt;
        ///        Hébergement :&lt;br /&gt;
        ///        Microsoft Windows Azure.
        /// </summary>
        public static string ImprintDescription {
            get {
                return ResourceManager.GetString("ImprintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à eWorky c&apos;est également une communauté active d’indépendants, de nomades, de télétravailleurs, d’entrepreneurs et d’étudiants adeptes de mobilité et de coworking. Rejoignez la communauté et partagez vous aussi vos lieux de travail préférés sur le site..
        /// </summary>
        public static string JoinCommunity {
            get {
                return ResourceManager.GetString("JoinCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message Envoyé.
        /// </summary>
        public static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre message a été envoyé avec succes, nos services vont vous répondre rapidement.
        /// </summary>
        public static string MailWellSent {
            get {
                return ResourceManager.GetString("MailWellSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus de critères.
        /// </summary>
        public static string MoreCriterias {
            get {
                return ResourceManager.GetString("MoreCriterias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Presse.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un lieu de travail.
        /// </summary>
        public static string SearchWorkspace {
            get {
                return ResourceManager.GetString("SearchWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partager..
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faites profiter la communauté de vos bons plans&lt;br /&gt;
        ///                ou de votre propre espace de travail.
        /// </summary>
        public static string ShareTips {
            get {
                return ResourceManager.GetString("ShareTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Puis on a eu mauvaise conscience, on s’est dit que c’était dommage de ne pas vous en faire profiter aussi. Soyez donc les bienvenus dans la communauté eWorky !.
        /// </summary>
        public static string ShareWithYou {
            get {
                return ResourceManager.GetString("ShareWithYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous trouverez bientôt ici également un dossier de presse sur eWorky..
        /// </summary>
        public static string SoonPressKit {
            get {
                return ResourceManager.GetString("SoonPressKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes journaliste et vous souhaitez rédiger un article ou réaliser un reportage sur eWorky ? Vous avez besoin d&apos;un dossier sur le développement du télétravail en France ? Vous cherchez des DRH à interviewer sur ces sujets ? Contactez nous à {0}.
        /// </summary>
        public static string SpeechForJournalists {
            get {
                return ResourceManager.GetString("SpeechForJournalists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proposer des lieux de travail.
        /// </summary>
        public static string SubmitWorkplace {
            get {
                return ResourceManager.GetString("SubmitWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fonctionnement d’eWorky.
        /// </summary>
        public static string UsingOfEWorky {
            get {
                return ResourceManager.GetString("UsingOfEWorky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Et surtout beaucoup beaucoup de générosité.
        /// </summary>
        public static string VeryGenerous {
            get {
                return ResourceManager.GetString("VeryGenerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue sur eWorky !.
        /// </summary>
        public static string WelcomeToEWorky {
            get {
                return ResourceManager.GetString("WelcomeToEWorky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quoi ?.
        /// </summary>
        public static string What {
            get {
                return ResourceManager.GetString("What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Où ?.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qui sommes-nous ?.
        /// </summary>
        public static string WhoAreWe {
            get {
                return ResourceManager.GetString("WhoAreWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lieux de travail.
        /// </summary>
        public static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
    }
}
