//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Home.HomeString", typeof(HomeString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposer un nouvel espace de travail.
        /// </summary>
        public static string AddPlaceTitle {
            get {
                return ResourceManager.GetString("AddPlaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coworking, partage de bureaux, cafés wifi.
        /// </summary>
        public static string BestWorkspace {
            get {
                return ResourceManager.GetString("BestWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le blog eWorky.
        /// </summary>
        public static string BlogTitle {
            get {
                return ResourceManager.GetString("BlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez le type d&apos;espace que vous voulez ajouter..
        /// </summary>
        public static string ChooseForm {
            get {
                return ResourceManager.GetString("ChooseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactez-nous.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un lieu de travail payant.
        /// </summary>
        public static string CostSpace {
            get {
                return ResourceManager.GetString("CostSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouvez un lieu de travail où vous voulez : bureaux à partager, centre d&apos;affaires, espaces de coworking, café wifi, salle de réunion ou de conférence..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2012 eWorky.
        /// </summary>
        public static string eWorky {
            get {
                return ResourceManager.GetString("eWorky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex : Pau, Oise, rue Rivoli Paris, 92200, ....
        /// </summary>
        public static string ExampleLocation {
            get {
                return ResourceManager.GetString("ExampleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouver le meilleur endroit pour travailler.
        /// </summary>
        public static string FindTheBesPlace1 {
            get {
                return ResourceManager.GetString("FindTheBesPlace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parmi &lt;em&gt;{0:### ### ###}&lt;/em&gt; espaces de coworking, cafés wifi, centres d&apos;affaires, bureaux partagés.
        /// </summary>
        public static string FindTheBesPlace2 {
            get {
                return ResourceManager.GetString("FindTheBesPlace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un lieu de travail gratuit.
        /// </summary>
        public static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions légales.
        /// </summary>
        public static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce site web est édité par :&lt;br /&gt;
        ///        Omnicentre SAS&lt;br /&gt;
        ///        Société par actions simplifiée au capital de 20 740 € - RCS PARIS 529 309 668&lt;br /&gt;
        ///        Siège social : 57, rue de Lille, 75 007 Paris&lt;br /&gt;
        ///        &lt;br /&gt;
        ///        Contact :&lt;br /&gt;
        ///        {0}&lt;br /&gt;
        ///        &lt;br /&gt;
        ///        Hébergement :&lt;br /&gt;
        ///        Microsoft Windows Azure.
        /// </summary>
        public static string ImprintDescription {
            get {
                return ResourceManager.GetString("ImprintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky est le portail du lieu de travail en France.
        /// </summary>
        public static string IntroWhoAreWe {
            get {
                return ResourceManager.GetString("IntroWhoAreWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message a été envoyé avec succès, nos services vont vous répondre rapidement..
        /// </summary>
        public static string MailWellSent {
            get {
                return ResourceManager.GetString("MailWellSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message a été envoyé avec succès!.
        /// </summary>
        public static string MailWellSent2 {
            get {
                return ResourceManager.GetString("MailWellSent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget maximal (€).
        /// </summary>
        public static string MaxRate {
            get {
                return ResourceManager.GetString("MaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface minimale (m²).
        /// </summary>
        public static string MinSurface {
            get {
                return ResourceManager.GetString("MinSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus de critères.
        /// </summary>
        public static string MoreCriterias {
            get {
                return ResourceManager.GetString("MoreCriterias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presse.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présentation des options de l&apos;espace gérant sur eWorky..
        /// </summary>
        public static string PricingDescription {
            get {
                return ResourceManager.GetString("PricingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une annonce de location de locaux.
        /// </summary>
        public static string RentalAd {
            get {
                return ResourceManager.GetString("RentalAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - bureaux professionnels&lt;br /&gt;- fond de commerce&lt;br /&gt;- local commercial, etc..
        /// </summary>
        public static string RentSpeech {
            get {
                return ResourceManager.GetString("RentSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réservation.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Centre d&apos;affaires, espace voyageurs&lt;br /&gt;- Espace de coworking&lt;br /&gt;- Télécentre, etc..
        /// </summary>
        public static string ReserveSpeech {
            get {
                return ResourceManager.GetString("ReserveSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Café internet, spot wifi&lt;br /&gt;- Espace public numérique&lt;br /&gt;- Bibliothèque, musée, etc..
        /// </summary>
        public static string SearchSpeech {
            get {
                return ResourceManager.GetString("SearchSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un espace partagé.
        /// </summary>
        public static string SharedOffice {
            get {
                return ResourceManager.GetString("SharedOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez des postes de travail inutilisés dans votre entreprise ? Partagez-les sur eWorky et profitez de revenus supplémentaires !.
        /// </summary>
        public static string SharedOfficeSpeach {
            get {
                return ResourceManager.GetString("SharedOfficeSpeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} à {1}.
        /// </summary>
        public static string SliderItemDesc {
            get {
                return ResourceManager.GetString("SliderItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Et bientôt plein d’autres fonctionnalités..
        /// </summary>
        public static string SoonLotofFeatures {
            get {
                return ResourceManager.GetString("SoonLotofFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes journaliste et vous souhaitez rédiger un article ou réaliser un reportage sur eWorky ? Vous avez besoin d&apos;un dossier sur le développement du télétravail en France ? Vous cherchez des DRH à interviewer sur ces sujets ? Contactez-nous à {0}..
        /// </summary>
        public static string SpeechForJournalists {
            get {
                return ResourceManager.GetString("SpeechForJournalists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ils en parlent.
        /// </summary>
        public static string TalkAboutUs {
            get {
                return ResourceManager.GetString("TalkAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;équipe.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olivier Brun.
        /// </summary>
        public static string Team_Member_1 {
            get {
                return ResourceManager.GetString("Team_Member_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitant à Paris, Olivier s’occupe chez eWorky de la stratégie et du storyboarding. En plus d’être aussi discret dans ses échanges en open-space qu’un poissonnier un samedi matin à 5h du mat à Rungis, Olivier est un grand fan de marche à pied et un végétarien convaincu. Mais par-dessus tout, Olivier glorifie les designs épurés et voue un culte à la suppression des boutons inutiles et des fautes d’orthographe..
        /// </summary>
        public static string Team_Member_1_Text {
            get {
                return ResourceManager.GetString("Team_Member_1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cécilia Durieu.
        /// </summary>
        public static string Team_Member_2 {
            get {
                return ResourceManager.GetString("Team_Member_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cécilia s&apos;occupe du développement commercial, des relations presse et du financement d&apos;eWorky. Elle travaille depuis Grenoble et attention, elle ne supporte pas qu&apos;on dise du mal de sa région montagnarde ! Optimiste, hyperactive et grande fan des agendas pleins à craquer et des deadlines serrées, elle est très impliquée dans la promotion du numérique et de l&apos;entrepreneuriat, en tant que co-présidente du Cercle des Jeunes Entrepreneurs notamment. Lorsqu&apos;elle parvient à trouver un peu de temps libre, elle aim [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Team_Member_2_Text {
            get {
                return ResourceManager.GetString("Team_Member_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahir Iftikhar.
        /// </summary>
        public static string Team_Member_3 {
            get {
                return ResourceManager.GetString("Team_Member_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahir est LE spécialiste du développement, tellement spécialiste qu’on a parfois du mal à comprendre tout ce qu’il nous dit. Lecteur de Dostoïevski et de Camus, il est aussi à l’aise dans la programmation que dans l’engloutissement constant de cafés, gâteaux et barres chocolatées en tout genre. Originiaire des Ulis (oui comme Thierry Henry), il a déjà fait de la capoeira, de la plongée, et sa propension à semer les fautes d’orthographe comme les paquets de biscuits vides derrière lui compense le zèle avec l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Team_Member_3_Text {
            get {
                return ResourceManager.GetString("Team_Member_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marc Labrude.
        /// </summary>
        public static string Team_Member_4 {
            get {
                return ResourceManager.GetString("Team_Member_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marc est en charge du business development sur les marchés hispanophones. &quot;Marco&quot; est basé à Saragosse dans cette ville qui l&apos;a séduit par sa douceur de vivre et son exceptionnelle densité de bar à tapas. Marc est à l&apos;image du pays dans lequel il a choisi de poser ses valises : chaleureux, fêtard, gourmand, sportif. D&apos;ailleurs, on ne sait pas exactement à quoi il se dope pour apporter tant de dynamisme à l&apos;équipe mais on suspecte un savant mélange de Cacique, d&apos;huile d&apos;olive et de chorizo..
        /// </summary>
        public static string Team_Member_4_Text {
            get {
                return ResourceManager.GetString("Team_Member_4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présentation de l&apos;equipe d&apos;eWorky !.
        /// </summary>
        public static string TeamDescription {
            get {
                return ResourceManager.GetString("TeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’équipe eWorky a plein de projets dans les cartons pour simplifier le travail ! Alors suivez-nos actualités sur Facebook, Twitter, Google+, etc..
        /// </summary>
        public static string Teamworky {
            get {
                return ResourceManager.GetString("Teamworky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un jour.
        /// </summary>
        public static string TimeAgo_day {
            get {
                return ResourceManager.GetString("TimeAgo_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d jours.
        /// </summary>
        public static string TimeAgo_days {
            get {
                return ResourceManager.GetString("TimeAgo_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to une heure.
        /// </summary>
        public static string TimeAgo_hour {
            get {
                return ResourceManager.GetString("TimeAgo_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d heures.
        /// </summary>
        public static string TimeAgo_hours {
            get {
                return ResourceManager.GetString("TimeAgo_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to une minute.
        /// </summary>
        public static string TimeAgo_minute {
            get {
                return ResourceManager.GetString("TimeAgo_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d minutes.
        /// </summary>
        public static string TimeAgo_minutes {
            get {
                return ResourceManager.GetString("TimeAgo_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un mois.
        /// </summary>
        public static string TimeAgo_month {
            get {
                return ResourceManager.GetString("TimeAgo_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d mois.
        /// </summary>
        public static string TimeAgo_months {
            get {
                return ResourceManager.GetString("TimeAgo_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a.
        /// </summary>
        public static string TimeAgo_prefixAgo {
            get {
                return ResourceManager.GetString("TimeAgo_prefixAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d&apos;ici.
        /// </summary>
        public static string TimeAgo_prefixFromNow {
            get {
                return ResourceManager.GetString("TimeAgo_prefixFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moins d&apos;une minute.
        /// </summary>
        public static string TimeAgo_seconds {
            get {
                return ResourceManager.GetString("TimeAgo_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string TimeAgo_suffixAgo {
            get {
                return ResourceManager.GetString("TimeAgo_suffixAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string TimeAgo_suffixFromNow {
            get {
                return ResourceManager.GetString("TimeAgo_suffixFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un an.
        /// </summary>
        public static string TimeAgo_year {
            get {
                return ResourceManager.GetString("TimeAgo_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d ans.
        /// </summary>
        public static string TimeAgo_years {
            get {
                return ResourceManager.GetString("TimeAgo_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonctionnement d’eWorky.
        /// </summary>
        public static string UsingOfEWorky {
            get {
                return ResourceManager.GetString("UsingOfEWorky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous croyons que :.
        /// </summary>
        public static string WeThinkThat {
            get {
                return ResourceManager.GetString("WeThinkThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lieu de travail de demain se recentrera sur l’humain plus que sur l’entreprise, et sera un endroit convivial, propice aux échanges. On prendra du plaisir à aller travailler..
        /// </summary>
        public static string WeThinkThat_Text1 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si vous pensez ainsi, rejoignez-nous !.
        /// </summary>
        public static string WeThinkThat_Text10 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour inventer ensemble le lieu de travail de demain, il est nécessaire d’explorer, de tester, d’échanger et surtout de se lancer à l’eau..
        /// </summary>
        public static string WeThinkThat_Text2 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’avènement de nouveaux modes de travail est une opportunité pour un nouveau contrat social dans lequel l’autonomie succède à la subordination, la créativité à l’obéissance, la responsabilité au contrôle hiérarchique..
        /// </summary>
        public static string WeThinkThat_Text3 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’ouverture aux autres, le partage et la collaboration sont essentiels à l’épanouissement personnel et au bon équilibre d’un lieu de travail..
        /// </summary>
        public static string WeThinkThat_Text4 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les travailleurs ont besoin de moments de contact et d’échanges plus humains dans leur journée. Il faut décloisonner nos activités, remplacer la contrainte par la coopération et la co-création en créant des collectifs de travail virtuels..
        /// </summary>
        public static string WeThinkThat_Text5 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lieu de travail ne sera plus unique mais multiple, parfois dématérialisé et le plus souvent adapté à la tâche, au secteur et à la personnalité du travailleur..
        /// </summary>
        public static string WeThinkThat_Text6 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le développement durable est une priorité non pas de demain mais d’aujourd’hui, c’est pourquoi nos nouveaux lieux et modes de travail doivent naturellement prendre en compte le respect de notre planète..
        /// </summary>
        public static string WeThinkThat_Text7 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le monde évolue à une vitesse vertigineuse sous l’impulsion des technologies de l’information. L’organisation du travail, immuable depuis des décennies, doit elle aussi connaître sa révolution..
        /// </summary>
        public static string WeThinkThat_Text8 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En repensant l’espace de travail grâce aux lieux de coworking et aux espaces partagés, on peut transformer le travail au quotidien, notre rapport aux autres et notre monde. Le lieu de travail doit être le théâtre mais aussi l’acteur de ce changement..
        /// </summary>
        public static string WeThinkThat_Text9 {
            get {
                return ResourceManager.GetString("WeThinkThat_Text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que cherchez-vous ?.
        /// </summary>
        public static string What {
            get {
                return ResourceManager.GetString("What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Où cherchez-vous ?.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui sommes-nous ?.
        /// </summary>
        public static string WhoAreWe {
            get {
                return ResourceManager.GetString("WhoAreWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky a été créé en 2011 par trois jeunes entrepreneurs, en réponse à un besoin simple : pouvoir accéder à un wifi, louer une salle de réunion ou de formation, de façon ponctuelle, et dans des villes différentes. L’idée d’une plate-forme collaborative de recherche du lieu de travail a ensuite rapidement fait son chemin..
        /// </summary>
        public static string WhoAreWe_Text1 {
            get {
                return ResourceManager.GetString("WhoAreWe_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky, c’est donc le plaisir de partager des lieux de travail en tout genre, et d’échanger sur les différentes expériences vécues dans ces lieux. Notre communauté est composée d’utilisateurs passionnés, voulant découvrir ou proposer une grande diversité d’espaces, adaptés à chaque besoin..
        /// </summary>
        public static string WhoAreWe_Text2 {
            get {
                return ResourceManager.GetString("WhoAreWe_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À votre tour, rejoignez la communauté eWorky ! .
        /// </summary>
        public static string WhoAreWe_Text3 {
            get {
                return ResourceManager.GetString("WhoAreWe_Text3", resourceCulture);
            }
        }
    }
}
