//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HowItWorksString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HowItWorksString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Home.HowItWorksString", typeof(HowItWorksString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour gérer votre espace sur eWorky, faites la demande {0}.
        /// </summary>
        public static string AccessBO {
            get {
                return ResourceManager.GetString("AccessBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via le formulaire de contact.
        /// </summary>
        public static string AccessBOLink {
            get {
                return ResourceManager.GetString("AccessBOLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accéder à l&apos;espace gérant.
        /// </summary>
        public static string AccessBOTitle {
            get {
                return ResourceManager.GetString("AccessBOTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réservez et payez en ligne votre réservation de salle de réunion ou votre abonnement à un espace de coworking.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réserver.
        /// </summary>
        public static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaque lieu propose différentes offres. Consultez-les et réservez celle dont vous avez besoin !.
        /// </summary>
        public static string BookUser {
            get {
                return ResourceManager.GetString("BookUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réserver.
        /// </summary>
        public static string BookUserTitle {
            get {
                return ResourceManager.GetString("BookUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répondez en un clic aux demandes de réservation et de devis des utilisateurs et encaissez directement sur votre compte.
        /// </summary>
        public static string Commercialize {
            get {
                return ResourceManager.GetString("Commercialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercialiser.
        /// </summary>
        public static string CommercializeTitle {
            get {
                return ResourceManager.GetString("CommercializeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echangez, discutez et animez son espace grâce aux pages dédiées aux espaces de coworking.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echanger avec ses coworkers.
        /// </summary>
        public static string ExchangeTitle {
            get {
                return ResourceManager.GetString("ExchangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une fois votre demande validée, profitez gratuitement de toutes les fonctionnalités de gestion de votre espace.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&apos;est parti !.
        /// </summary>
        public static string GoTitle {
            get {
                return ResourceManager.GetString("GoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assurez un suivi commercial, émettez les factures et pilotez l’activité de votre espace de travail.
        /// </summary>
        public static string HandleClients {
            get {
                return ResourceManager.GetString("HandleClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer vos clients.
        /// </summary>
        public static string HandleClientsTitle {
            get {
                return ResourceManager.GetString("HandleClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérez gratuitement les réservations, les plannings, les consommations annexes, les tarifs et les abonnements de vos offres.
        /// </summary>
        public static string HandleSpace {
            get {
                return ResourceManager.GetString("HandleSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer votre espace.
        /// </summary>
        public static string HandleSpaceTitle {
            get {
                return ResourceManager.GetString("HandleSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment faire ?.
        /// </summary>
        public static string HowDoIt {
            get {
                return ResourceManager.GetString("HowDoIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment ça marche.
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky est un marché ouvert du lieu de travail.
        /// </summary>
        public static string HowItWorksHead {
            get {
                return ResourceManager.GetString("HowItWorksHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajoutez, notez et commentez les lieux de travail pour aider toute la communauté dans ses recherches.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre la communauté.
        /// </summary>
        public static string JoinTitle {
            get {
                return ResourceManager.GetString("JoinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intégrez gratuitement la plus grande base de lieux de travail en Europe avec une fiche complète décrivant vos offres et vos services.
        /// </summary>
        public static string MakeFamous {
            get {
                return ResourceManager.GetString("MakeFamous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faire connaître.
        /// </summary>
        public static string MakeFamousTitle {
            get {
                return ResourceManager.GetString("MakeFamousTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérant.
        /// </summary>
        public static string OwnerTitle {
            get {
                return ResourceManager.GetString("OwnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je suis gérant.
        /// </summary>
        public static string OwnerTutorial {
            get {
                return ResourceManager.GetString("OwnerTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une fois votre demande de réservation confirmée par le gérant de l’espace, vous pouvez directement payer en ligne avec votre carte de paiement.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer en ligne.
        /// </summary>
        public static string PayTitle {
            get {
                return ResourceManager.GetString("PayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créez gratuitement {0} en précisant que vous en êtes propriétaire.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to une fiche pour votre lieu.
        /// </summary>
        public static string ReferenceLink {
            get {
                return ResourceManager.GetString("ReferenceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réferencer.
        /// </summary>
        public static string RefererenceTitle {
            get {
                return ResourceManager.GetString("RefererenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous inscrire gratuitement.
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour gérer un lieu sur eWorky, vous devez {0} en créant un compte ou en vous identifiant par Facebook.
        /// </summary>
        public static string RegisterOwner {
            get {
                return ResourceManager.GetString("RegisterOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S’inscrire.
        /// </summary>
        public static string RegisterOwnerTitle {
            get {
                return ResourceManager.GetString("RegisterOwnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour profiter pleinement d’eWorky, vous devez {0} en créant un compte ou en vous identifiant par Facebook.
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string RegisterUserTitle {
            get {
                return ResourceManager.GetString("RegisterUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouvez un café wifi, une salle de réunion ou une place de coworking parmi la plus grande base de lieux de travail en Europe.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherchez l’espace de travail dont vous avez besoin par lieu, par nom, par services ou par type de lieu.
        /// </summary>
        public static string SearchUser {
            get {
                return ResourceManager.GetString("SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string SearchUserTitle {
            get {
                return ResourceManager.GetString("SearchUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur.
        /// </summary>
        public static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je suis utilisateur.
        /// </summary>
        public static string UserTutorial {
            get {
                return ResourceManager.GetString("UserTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky vous aide à gérer un lieu de travail mais ne remplacera jamais votre convivialité et votre accueil !.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueillir.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky vous aide à trouver un lieu de travail mais pas à travailler, alors au boulot !.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au travail.
        /// </summary>
        public static string WorkTitle {
            get {
                return ResourceManager.GetString("WorkTitle", resourceCulture);
            }
        }
    }
}
