//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.225
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareOffice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareOffice() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Home.ShareOffice", typeof(ShareOffice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obtenir l&apos;espace gérant.
        /// </summary>
        public static string AccessBO {
            get {
                return ResourceManager.GetString("AccessBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partager immédiatement mes bureaux.
        /// </summary>
        public static string AddSpace {
            get {
                return ResourceManager.GetString("AddSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez de collaborer et d’échanger avec votre hôte et bénéficiez ainsi de l’apport mutuel et de l’enrichissement collectif.
        /// </summary>
        public static string ForBoth1 {
            get {
                return ResourceManager.GetString("ForBoth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Découvrez au contact des autres structures des opportunités de nouveaux marchés, partagez des ressources et des prospects.
        /// </summary>
        public static string ForBoth2 {
            get {
                return ResourceManager.GetString("ForBoth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Développez un environnement dynamique et créatif pour vos deux structures.
        /// </summary>
        public static string ForBoth3 {
            get {
                return ResourceManager.GetString("ForBoth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enrichissez-vous d’échanges !.
        /// </summary>
        public static string ForBothHead1 {
            get {
                return ResourceManager.GetString("ForBothHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Construisez votre réseau !.
        /// </summary>
        public static string ForBothHead2 {
            get {
                return ResourceManager.GetString("ForBothHead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriétaire.
        /// </summary>
        public static string ForOwner {
            get {
                return ResourceManager.GetString("ForOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proposez gratuitement et en quelques clics votre espace sur eWorky.
        /// </summary>
        public static string ForOwner1 {
            get {
                return ResourceManager.GetString("ForOwner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gagnez plusieurs milliers d&apos;euros par an et par poste de travail.
        /// </summary>
        public static string ForOwner2 {
            get {
                return ResourceManager.GetString("ForOwner2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous nous occupons de tout ! Tout est automatique, de la recherche d’occupants à l’encaissement des fonds.
        /// </summary>
        public static string ForOwner3 {
            get {
                return ResourceManager.GetString("ForOwner3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous disposez de bureaux inoccupés ?.
        /// </summary>
        public static string ForOwnerHead1 {
            get {
                return ResourceManager.GetString("ForOwnerHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous préféreriez en tirer un revenu plutôt que d’y entasser vos vieilles factures ?.
        /// </summary>
        public static string ForOwnerHead2 {
            get {
                return ResourceManager.GetString("ForOwnerHead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locataire.
        /// </summary>
        public static string ForTenant {
            get {
                return ResourceManager.GetString("ForTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trouvez un poste de travail jusqu’à cinq fois moins cher qu’en location traditionnelle ou qu’en centre d’affaires.
        /// </summary>
        public static string ForTenant1 {
            get {
                return ResourceManager.GetString("ForTenant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profitez de la flexibilité du partage, avec des locations à la journée, à la semaine, au mois….
        /// </summary>
        public static string ForTenant2 {
            get {
                return ResourceManager.GetString("ForTenant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réservez votre espace et payez en quelques clics !.
        /// </summary>
        public static string ForTenant3 {
            get {
                return ResourceManager.GetString("ForTenant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes une TPE ou un indépendant ?.
        /// </summary>
        public static string ForTenantHead1 {
            get {
                return ResourceManager.GetString("ForTenantHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous recherchez un espace pour votre activité ?.
        /// </summary>
        public static string ForTenantHead2 {
            get {
                return ResourceManager.GetString("ForTenantHead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le partage s’effectue généralement sous forme de &lt;b&gt;sous-location&lt;/b&gt; : une société loue l&apos;ensemble des bureaux et sous-loue ensuite à d&apos;autres sociétés. Une société souhaitant proposer une sous location doit obtenir un accord écrit de son propriétaire à défaut de l&apos;avoir prévu dans le bail..
        /// </summary>
        public static string Legally1 {
            get {
                return ResourceManager.GetString("Legally1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mais chez eWorky nous recommandons une solution, plus souple : &lt;b&gt;le contrat de prestation de service&lt;/b&gt;. Il s’agit d’un acte par lequel une personne s’oblige, contre rémunération,  à effectuer pour une autre personne une prestation de services..
        /// </summary>
        public static string Legally2 {
            get {
                return ResourceManager.GetString("Legally2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans le cas présent il s’agit de la mise à disposition d’un local et de l’équipement qui lui est rattaché, voire d’autres services (ménage, etc.). Et pour vous aider, &lt;b&gt;eWorky&lt;/b&gt; met à votre disposition des &lt;b&gt;contrats types&lt;/b&gt;, et vous propose de les &lt;b&gt;gérer directement&lt;/b&gt; à partir du site !.
        /// </summary>
        public static string Legally3 {
            get {
                return ResourceManager.GetString("Legally3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A noter que les deux types de contrats peuvent également s’accompagner d’une domiciliation de l’entreprise..
        /// </summary>
        public static string Legally4 {
            get {
                return ResourceManager.GetString("Legally4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Et juridiquement, ça se passe comment ?.
        /// </summary>
        public static string LegallyTitle {
            get {
                return ResourceManager.GetString("LegallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trouver et partager un bureau, une salle de réunion, une salle de conférence, un local en colocation et sous-location ou proposer vos bureaux et salles à louer.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partager un bureau | eWorky, toutes les offres de bureaux partagés.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partager un bureau.
        /// </summary>
        public static string ShareOfficeMenu {
            get {
                return ResourceManager.GetString("ShareOfficeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partager son bureau : pourquoi et comment ?.
        /// </summary>
        public static string ShareOfficeTitle {
            get {
                return ResourceManager.GetString("ShareOfficeTitle", resourceCulture);
            }
        }
    }
}
