//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.BackOffice {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BackOfficeString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackOfficeString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.BackOffice.BackOfficeString", typeof(BackOfficeString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à l&apos;espace gérant.
        /// </summary>
        public static string BackToOwnerSpace {
            get {
                return ResourceManager.GetString("BackToOwnerSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiche client.
        /// </summary>
        public static string CustomerSheet {
            get {
                return ResourceManager.GetString("CustomerSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messagerie électronique.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez aucune réservation. Pour effectuer une demande de réservation, allez sur la fiche du lieu souhaité..
        /// </summary>
        public static string EmptyBookHistoric {
            get {
                return ResourceManager.GetString("EmptyBookHistoric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez reçu aucune notification..
        /// </summary>
        public static string EmptyNews {
            get {
                return ResourceManager.GetString("EmptyNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez fait aucune demande de devis. Pour effectuer une demande de devis, allez sur la fiche du lieu souhaité..
        /// </summary>
        public static string EmptyQuotationHistoric {
            get {
                return ResourceManager.GetString("EmptyQuotationHistoric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historiques.
        /// </summary>
        public static string Historic {
            get {
                return ResourceManager.GetString("Historic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernières actualités.
        /// </summary>
        public static string LastNews {
            get {
                return ResourceManager.GetString("LastNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface de gestion de {0}.
        /// </summary>
        public static string ManagementTitle {
            get {
                return ResourceManager.GetString("ManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membre.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom, Prénom.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour proposer une offre à la réservation, vous devez préalablement indiquer l’adresse électronique associée à votre compte PayPal dans votre Profil..
        /// </summary>
        public static string NeedInfoPaypal {
            get {
                return ResourceManager.GetString("NeedInfoPaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez aucune réservation en cours. Pour consulter vos réservations archivées, allez dans la section {0}..
        /// </summary>
        public static string NoCurrentBooking {
            get {
                return ResourceManager.GetString("NoCurrentBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez aucune demande de vis en cours. Pour consulter vos demandes de devis archivées, allez dans la section {0}..
        /// </summary>
        public static string NoCurrentQuotation {
            get {
                return ResourceManager.GetString("NoCurrentQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez aucune réservation en cours. Pour consulter vos réservations archivées, allez dans la section {0}..
        /// </summary>
        public static string NoWorkingBooking {
            get {
                return ResourceManager.GetString("NoWorkingBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez aucune demande de devis en cours. Pour consulter vos demandes de devis archivées, allez dans la section {0}..
        /// </summary>
        public static string NoWorkingQuotation {
            get {
                return ResourceManager.GetString("NoWorkingQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de réservations.
        /// </summary>
        public static string NumberBooking {
            get {
                return ResourceManager.GetString("NumberBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offres.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérant.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espace gérant.
        /// </summary>
        public static string OwnerSpace {
            get {
                return ResourceManager.GetString("OwnerSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les informations de paiements ont été mis à jour.
        /// </summary>
        public static string PaymentInfoModified {
            get {
                return ResourceManager.GetString("PaymentInfoModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tél..
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès direct à la gestion des lieux.
        /// </summary>
        public static string WorkplacesDirectAccess {
            get {
                return ResourceManager.GetString("WorkplacesDirectAccess", resourceCulture);
            }
        }
    }
}
