CREATE TABLE [dbo].[Localisation] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [Name]                 NVARCHAR (256) NOT NULL,
    [TypeValue]            INT            CONSTRAINT [DF__Localisat__TypeV__4D94879B] DEFAULT ((0)) NOT NULL,
    [Adress]               NVARCHAR (256) NOT NULL,
    [PostalCode]           NVARCHAR (10)   NOT NULL,
    [City]                 NVARCHAR (256)  NOT NULL,
    [Country]              NVARCHAR (256)  NOT NULL,
    [PhoneNumber]          NVARCHAR (50)   NULL,
    [Mail]                 NVARCHAR (256)  NULL,
    [Fax]                  NVARCHAR (50)   NULL,
    [WebSite]              NVARCHAR (256)  NULL,
	[Facebook]             NVARCHAR (256)  NULL,
	[Twitter]              NVARCHAR (256)  NULL,
    [Description]          NVARCHAR (MAX) NULL,
    [Latitude]             FLOAT (53)     NOT NULL,
    [Longitude]            FLOAT (53)     NOT NULL,
    [OwnerID]              INT            CONSTRAINT [DF__Localisat__Owner__5535A963] DEFAULT ((0)) NULL,
    [Bookable]             BIT            CONSTRAINT [DF__Localisat__Booka__5629CD9C] DEFAULT ((0)) NOT NULL,
    [MonOpen]              SMALLDATETIME  NULL,
    [MonClose]             SMALLDATETIME  NULL,
    [MonOpen2]             SMALLDATETIME  NULL,
    [MonClose2]            SMALLDATETIME  NULL,
    [TueOpen]              SMALLDATETIME  NULL,
    [TueClose]             SMALLDATETIME  NULL,
    [TueOpen2]             SMALLDATETIME  NULL,
    [TueClose2]            SMALLDATETIME  NULL,
    [WedOpen]              SMALLDATETIME  NULL,
    [WedClose]             SMALLDATETIME  NULL,
    [WedOpen2]             SMALLDATETIME  NULL,
    [WedClose2]            SMALLDATETIME  NULL,
    [ThuOpen]              SMALLDATETIME  NULL,
    [ThuClose]             SMALLDATETIME  NULL,
    [ThuOpen2]             SMALLDATETIME  NULL,
    [ThuClose2]            SMALLDATETIME  NULL,
    [FriOpen]              SMALLDATETIME  NULL,
    [FriClose]             SMALLDATETIME  NULL,
    [FriOpen2]             SMALLDATETIME  NULL,
    [FriClose2]            SMALLDATETIME  NULL,
    [SatOpen]              SMALLDATETIME  NULL,
    [SatClose]             SMALLDATETIME  NULL,
    [SatOpen2]             SMALLDATETIME  NULL,
    [SatClose2]            SMALLDATETIME  NULL,
    [SunOpen]              SMALLDATETIME  NULL,
    [SunClose]             SMALLDATETIME  NULL,
    [SunOpen2]             SMALLDATETIME  NULL,
    [SunClose2]            SMALLDATETIME  NULL,
    [PublicTransportation] NVARCHAR (256) NULL,
    [Station]              NVARCHAR (256) NULL,
    [RoadAccess]           NVARCHAR (256) NULL,
    CONSTRAINT [PK_Localisation] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Localisation_Member] FOREIGN KEY ([OwnerID]) REFERENCES [dbo].[Member] ([MemberId]) ON DELETE NO ACTION ON UPDATE NO ACTION
);

