CREATE TABLE [dbo].[LocalisationData] (
    [ID]				INT             IDENTITY (1, 1) NOT NULL,
    [LocalisationID]	INT             NOT NULL,
    [CoffeePrice]		DECIMAL (18, 2) NULL,
    [MonOpenMorning]	SMALLDATETIME NULL,
	[MonCloseMorning]	SMALLDATETIME NULL, 
	[MonOpenAfter]		SMALLDATETIME NULL, 
	[MonCloseAfter]		SMALLDATETIME NULL, 
	[TueOpenMorning]	SMALLDATETIME NULL,
	[TueCloseMorning]	SMALLDATETIME NULL, 
	[TueOpenAfter]		SMALLDATETIME NULL, 
	[TueCloseAfter]		SMALLDATETIME NULL, 
	[WedOpenMorning]	SMALLDATETIME NULL,
	[WedCloseMorning]	SMALLDATETIME NULL, 
	[WedOpenAfter]		SMALLDATETIME NULL, 
	[WedCloseAfter]		SMALLDATETIME NULL, 
	[ThuOpenMorning]	SMALLDATETIME NULL,
	[ThuCloseMorning]	SMALLDATETIME NULL, 
	[ThuOpenAfter]		SMALLDATETIME NULL, 
	[ThuCloseAfter]		SMALLDATETIME NULL, 
	[FriOpenMorning]	SMALLDATETIME NULL,
	[FriCloseMorning]	SMALLDATETIME NULL, 
	[FriOpenAfter]		SMALLDATETIME NULL, 
	[FriCloseAfter]		SMALLDATETIME NULL, 
	[SatOpenMorning]	SMALLDATETIME NULL,
	[SatCloseMorning]	SMALLDATETIME NULL, 
	[SatOpenAfter]		SMALLDATETIME NULL, 
	[SatCloseAfter]		SMALLDATETIME NULL, 
	[SunOpenMorning]	SMALLDATETIME NULL,
	[SunCloseMorning]	SMALLDATETIME NULL, 
	[SunOpenAfter]		SMALLDATETIME NULL, 
	[SunCloseAfter]		SMALLDATETIME NULL, 
    CONSTRAINT [PK_LocalisationData] PRIMARY KEY CLUSTERED ([LocalisationID] ASC),
    CONSTRAINT [FK_LocalisationData_Localisation] FOREIGN KEY ([LocalisationID]) REFERENCES [dbo].[Localisation] ([ID]) ON DELETE CASCADE ON UPDATE NO ACTION
);

