//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkiResources.Views.Visitor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VisitorString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisitorString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkiResources.Views.Visitor.VisitorString", typeof(VisitorString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky en bêta privée.
        /// </summary>
        public static string EWBetaPrivate {
            get {
                return ResourceManager.GetString("EWBetaPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky.
        /// </summary>
        public static string eWorky {
            get {
                return ResourceManager.GetString("eWorky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n’avez pas reçu d&apos;identifiants pour tester eWorky. Laissez-nous votre email..
        /// </summary>
        public static string LetUsYourMail {
            get {
                return ResourceManager.GetString("LetUsYourMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour accéder à eWorky, saisissez les identifiants reçus par email..
        /// </summary>
        public static string SetUserMail {
            get {
                return ResourceManager.GetString("SetUserMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande a été envoyée avec succès! Nous vous enverrons vos identifiants prochainement..
        /// </summary>
        public static string SuccessAsk {
            get {
                return ResourceManager.GetString("SuccessAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous voulez nous suggérer une amélioration ou nous signaler un bug, une seule adresse :.
        /// </summary>
        public static string SugestBug {
            get {
                return ResourceManager.GetString("SugestBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
