//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiClientAuthorization
    {
        // Primitive properties
    
        public int Id { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public int ApiClientId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string Scope { get; set; }
        public Nullable<System.DateTime> ExpirationDateUtc { get; set; }
    
        // Navigation properties
    
        public virtual ApiClient ApiClient { get; set; }
        public virtual Member Member { get; set; }
    
    }
}
