//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalAccess
    {
        // Primitive properties
    
        public int Id { get; set; }
        public int RentalId { get; set; }
        public int Type { get; set; }
        public string Line { get; set; }
        public string Station { get; set; }
    
        // Navigation properties
    
        public virtual Rental Rental { get; set; }
    
    }
}
