//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        // Primitive properties
    
        public int Id { get; set; }
        public int MemberBookingId { get; set; }
        public int ReceiverId { get; set; }
        public decimal Amount { get; set; }
        public int PaymentType { get; set; }
        public int StatusId { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RequestId { get; set; }
    
        // Navigation properties
    
        public virtual MemberBooking MemberBooking { get; set; }
        public virtual Member Member { get; set; }
    
    }
}
