//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WelcomePeople
    {
        // Primitive properties
    
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int LocalisationId { get; set; }
        public string Description { get; set; }
        public string LocalisationPicture { get; set; }
        public bool Online { get; set; }
    
        // Navigation properties
    
        public virtual Localisation Localisation { get; set; }
        public virtual Member Member { get; set; }
    
    }
}
