//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkiSiteWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.MembersInGroups = new HashSet<MembersInGroup>();
        }
    
        // Primitive properties
    
        public int GroupId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<MembersInGroup> MembersInGroups { get; set; }
    
    }
}
