//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Rental {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RentalString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RentalString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Rental.RentalString", typeof(RentalString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string AccessLine {
            get {
                return ResourceManager.GetString("AccessLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string AccessStation {
            get {
                return ResourceManager.GetString("AccessStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de transport.
        /// </summary>
        public static string AccessType {
            get {
                return ResourceManager.GetString("AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affinner votre recherche.
        /// </summary>
        public static string AccurateSearch {
            get {
                return ResourceManager.GetString("AccurateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une annonce.
        /// </summary>
        public static string AddRental {
            get {
                return ResourceManager.GetString("AddRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse :.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (m²).
        /// </summary>
        public static string AreaUnit {
            get {
                return ResourceManager.GetString("AreaUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibilité.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de disponibilité.
        /// </summary>
        public static string AvailableDate {
            get {
                return ResourceManager.GetString("AvailableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultat(s) de votre recherche :.
        /// </summary>
        public static string BeginResultAnswer {
            get {
                return ResourceManager.GetString("BeginResultAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compris entre :.
        /// </summary>
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulter le profil :.
        /// </summary>
        public static string CheckProfile {
            get {
                return ResourceManager.GetString("CheckProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir une Date.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville :.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de contrat.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une alerte email.
        /// </summary>
        public static string CreateAlert {
            get {
                return ResourceManager.GetString("CreateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de dépôt :.
        /// </summary>
        public static string DateDrop {
            get {
                return ResourceManager.GetString("DateDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex : 31/12/2011.
        /// </summary>
        public static string DateExample {
            get {
                return ResourceManager.GetString("DateExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation :.
        /// </summary>
        public static string DiagnosticRate {
            get {
                return ResourceManager.GetString("DiagnosticRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer une annonce.
        /// </summary>
        public static string EditRental {
            get {
                return ResourceManager.GetString("EditRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email :.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annonce(s) trouvée(s).
        /// </summary>
        public static string EndResultAnswer {
            get {
                return ResourceManager.GetString("EndResultAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caratéristiques.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom :.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energie :.
        /// </summary>
        public static string HeatingType {
            get {
                return ResourceManager.GetString("HeatingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infos Admin.
        /// </summary>
        public static string InfoAdmin {
            get {
                return ResourceManager.GetString("InfoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations générales.
        /// </summary>
        public static string Infos {
            get {
                return ResourceManager.GetString("Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom :.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de Bail :.
        /// </summary>
        public static string LeaseType {
            get {
                return ResourceManager.GetString("LeaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation.
        /// </summary>
        public static string Localisation {
            get {
                return ResourceManager.GetString("Localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface maximum.
        /// </summary>
        public static string MaxArea {
            get {
                return ResourceManager.GetString("MaxArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix maximum.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface minimum.
        /// </summary>
        public static string MinArea {
            get {
                return ResourceManager.GetString("MinArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix minimum.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (€ cc).
        /// </summary>
        public static string MoneyUnit {
            get {
                return ResourceManager.GetString("MoneyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus de détail.
        /// </summary>
        public static string MoreDetail {
            get {
                return ResourceManager.GetString("MoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immédiatement.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriétaire.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° téléphone :.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieu.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal :.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer cette annonce.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référence.
        /// </summary>
        public static string Ref {
            get {
                return ResourceManager.GetString("Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référence annonce eWorky :.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annonce.
        /// </summary>
        public static string Rental {
            get {
                return ResourceManager.GetString("Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer l&apos;annonce.
        /// </summary>
        public static string RentalEdit {
            get {
                return ResourceManager.GetString("RentalEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer l&apos;annonce.
        /// </summary>
        public static string RentalSuppress {
            get {
                return ResourceManager.GetString("RentalSuppress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;annonce.
        /// </summary>
        public static string RentalType {
            get {
                return ResourceManager.GetString("RentalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mémoriser cette recherche.
        /// </summary>
        public static string SaveSearch {
            get {
                return ResourceManager.GetString("SaveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un email au propriétaire.
        /// </summary>
        public static string SendMailToOwner {
            get {
                return ResourceManager.GetString("SendMailToOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommander à un ami.
        /// </summary>
        public static string SendToFriend {
            get {
                return ResourceManager.GetString("SendToFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annonce mise à jour le.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pratique.
        /// </summary>
        public static string Usefull {
            get {
                return ResourceManager.GetString("Usefull", resourceCulture);
            }
        }
    }
}
