//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.225
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Localisation {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalisationString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalisationString() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Localisation.LocalisationString", typeof(LocalisationString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à à propos du lieu.
        /// </summary>
        public static string AboutPlace {
            get {
                return ResourceManager.GetString("AboutPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un espace.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouté par : .
        /// </summary>
        public static string AddBy {
            get {
                return ResourceManager.GetString("AddBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter des images....
        /// </summary>
        public static string AddPicture {
            get {
                return ResourceManager.GetString("AddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je suis le gérant du lieu.
        /// </summary>
        public static string AreYouOwner {
            get {
                return ResourceManager.GetString("AreYouOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réservation.
        /// </summary>
        public static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce lieu proposera bientôt des offres à la réservation.
        /// </summary>
        public static string BookingAvailableSoon {
            get {
                return ResourceManager.GetString("BookingAvailableSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande de réservation.
        /// </summary>
        public static string BookingForm {
            get {
                return ResourceManager.GetString("BookingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez indiquer précisément votre requête, ainsi que vos coordonnées. Votre message sera transmis directement au propriétaire du lieu..
        /// </summary>
        public static string BookingFormHelp {
            get {
                return ResourceManager.GetString("BookingFormHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réserver.
        /// </summary>
        public static string BookIt {
            get {
                return ResourceManager.GetString("BookIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer la suppression:.
        /// </summary>
        public static string ComfirmDelete {
            get {
                return ResourceManager.GetString("ComfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Communauté.
        /// </summary>
        public static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contacter cet espace.
        /// </summary>
        public static string ContactThisSpaceAction {
            get {
                return ResourceManager.GetString("ContactThisSpaceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu de travail supprimé.
        /// </summary>
        public static string DeletedWorkplace {
            get {
                return ResourceManager.GetString("DeletedWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effacer le lieu.
        /// </summary>
        public static string DeletePlace {
            get {
                return ResourceManager.GetString("DeletePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0.##} km.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer le lieu.
        /// </summary>
        public static string EditPlace {
            get {
                return ResourceManager.GetString("EditPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equipements.
        /// </summary>
        public static string Equipments {
            get {
                return ResourceManager.GetString("Equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à eWorkers.
        /// </summary>
        public static string Eworkers {
            get {
                return ResourceManager.GetString("Eworkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;avis des eWorkers.
        /// </summary>
        public static string EworkersOpinion {
            get {
                return ResourceManager.GetString("EworkersOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue..
        /// </summary>
        public static string execError {
            get {
                return ResourceManager.GetString("execError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page Facebook.
        /// </summary>
        public static string FacebookPage {
            get {
                return ResourceManager.GetString("FacebookPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre Timeline Facebook a été mise à jour.
        /// </summary>
        public static string FacebookUpdated {
            get {
                return ResourceManager.GetString("FacebookUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fax : .
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avis général.
        /// </summary>
        public static string GeneralOpinion {
            get {
                return ResourceManager.GetString("GeneralOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez vous le partager avec vos amis sur Facebook, afin d’améliorer sa visibilité ?.
        /// </summary>
        public static string ImproveVisibility {
            get {
                return ResourceManager.GetString("ImproveVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je travaille ici.
        /// </summary>
        public static string IWorkHere {
            get {
                return ResourceManager.GetString("IWorkHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernière édition par : .
        /// </summary>
        public static string LastEditBy {
            get {
                return ResourceManager.GetString("LastEditBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La liste des lieux vous a été envoyée.
        /// </summary>
        public static string ListLocSent {
            get {
                return ResourceManager.GetString("ListLocSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localisation.
        /// </summary>
        public static string Localisation {
            get {
                return ResourceManager.GetString("Localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La fiche du lieu a été créée..
        /// </summary>
        public static string LocHaveBeenCreate {
            get {
                return ResourceManager.GetString("LocHaveBeenCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le lieu a été supprimé..
        /// </summary>
        public static string LocHaveBeenDel {
            get {
                return ResourceManager.GetString("LocHaveBeenDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le lieu a été édité..
        /// </summary>
        public static string LocHaveBeenEdit {
            get {
                return ResourceManager.GetString("LocHaveBeenEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste complète des lieux.
        /// </summary>
        public static string LocList {
            get {
                return ResourceManager.GetString("LocList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A la Une.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mis à jour le {0}.
        /// </summary>
        public static string ModifiedThe {
            get {
                return ResourceManager.GetString("ModifiedThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus de détails.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention vous n&apos;avez pas précisé d&apos;offre pour cet espace. Veuillez en ajouter au moins une..
        /// </summary>
        public static string MustAddOffer {
            get {
                return ResourceManager.GetString("MustAddOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet espace vous intéresse ?.
        /// </summary>
        public static string NeedContactOfPlace {
            get {
                return ResourceManager.GetString("NeedContactOfPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contacter le gérant.
        /// </summary>
        public static string NeedContactOfPlaceAction {
            get {
                return ResourceManager.GetString("NeedContactOfPlaceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet espace vous intéresse ?.
        /// </summary>
        public static string NeedThisSpace {
            get {
                return ResourceManager.GetString("NeedThisSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réserver en ligne.
        /// </summary>
        public static string NeedThisSpaceAction {
            get {
                return ResourceManager.GetString("NeedThisSpaceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune photo disponible.
        /// </summary>
        public static string NoPictureAvailable {
            get {
                return ResourceManager.GetString("NoPictureAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à eWorky n&apos;a aucun lieu similaire à proximité à suggérer..
        /// </summary>
        public static string NoSuggestions {
            get {
                return ResourceManager.GetString("NoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d&apos;acces au lieu de travail.
        /// </summary>
        public static string NotAccessToWorkplace {
            get {
                return ResourceManager.GetString("NotAccessToWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non merci.
        /// </summary>
        public static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas à la Une.
        /// </summary>
        public static string NotMain {
            get {
                return ResourceManager.GetString("NotMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offres.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hors ligne.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En ligne.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vue d&apos;ensemble.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identité du gérant : .
        /// </summary>
        public static string OwnerIdentity {
            get {
                return ResourceManager.GetString("OwnerIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez confirmer la supression du lieu de travail:.
        /// </summary>
        public static string PleaseConfirmDelete {
            get {
                return ResourceManager.GetString("PleaseConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je vous recommande de découvrir ce lieu de travail : {0}.
        /// </summary>
        public static string Recommendation {
            get {
                return ResourceManager.GetString("Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horaires.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir les offres.
        /// </summary>
        public static string SeeOffers {
            get {
                return ResourceManager.GetString("SeeOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partager sur Facebook.
        /// </summary>
        public static string ShareOnFb {
            get {
                return ResourceManager.GetString("ShareOnFb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher les informations.
        /// </summary>
        public static string ShowContactInfo {
            get {
                return ResourceManager.GetString("ShowContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réseaux sociaux.
        /// </summary>
        public static string Socials {
            get {
                return ResourceManager.GetString("Socials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre espace a été ajouté avec succès !.
        /// </summary>
        public static string SuccessfullyAdded {
            get {
                return ResourceManager.GetString("SuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suggestion(s).
        /// </summary>
        public static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tel : .
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le : .
        /// </summary>
        public static string TheDate {
            get {
                return ResourceManager.GetString("TheDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tweet.
        /// </summary>
        public static string Tweet {
            get {
                return ResourceManager.GetString("Tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous sommes désolés, le lieu de travail séléctionné n&apos;existe pas ou a été effacé..
        /// </summary>
        public static string WorkplaceDeleted {
            get {
                return ResourceManager.GetString("WorkplaceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu de travail non trouvé..
        /// </summary>
        public static string WorkplaceNotFound {
            get {
                return ResourceManager.GetString("WorkplaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre lieu de travail a été supprimé avec succes.
        /// </summary>
        public static string WorkplaceWellDeleted {
            get {
                return ResourceManager.GetString("WorkplaceWellDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes désormais gérant de ce lieu !.
        /// </summary>
        public static string YouAreOwner {
            get {
                return ResourceManager.GetString("YouAreOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous connaissez les coordonnées de contact de cet espace de travail, saisissez-les grâce au formulaire d&apos;édition ou contactez-nous : contact@eworky.com..
        /// </summary>
        public static string YouKnowContactUs {
            get {
                return ResourceManager.GetString("YouKnowContactUs", resourceCulture);
            }
        }
    }
}
