//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Views.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Views.Profile.ProfileString", typeof(ProfileString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;a pas encore suggéré de lieu à la communauté des eWorkers..
        /// </summary>
        public static string AddedSpacesEmptyPublic {
            get {
                return ResourceManager.GetString("AddedSpacesEmptyPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez suggéré aucun lieu à la communauté des eWorkers. Pour ajouter un lieu, {0}..
        /// </summary>
        public static string AddedSpacesEmpy {
            get {
                return ResourceManager.GetString("AddedSpacesEmpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier mon mot de passe.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez commenté aucun lieu. Pour donner votre avis sur un espace de travail, allez en bas de sa fiche de description..
        /// </summary>
        public static string CommentsEmpy {
            get {
                return ResourceManager.GetString("CommentsEmpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas éditer plus de {0} en moins de 24h.
        /// </summary>
        public static string Edit24Hours {
            get {
                return ResourceManager.GetString("Edit24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer mon profil.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espaces favoris.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez ajouté aucun espace à vos favoris. Pour ajouter un espace à vos favoris, cliquez sur le bouton eWorky+ en haut de sa fiche de description..
        /// </summary>
        public static string FavoriteSpacesEmpty {
            get {
                return ResourceManager.GetString("FavoriteSpacesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;a pas ajouté d&apos;espace à ses favoris..
        /// </summary>
        public static string FavoriteSpacesEmptyPublic {
            get {
                return ResourceManager.GetString("FavoriteSpacesEmptyPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Facebook.
        /// </summary>
        public static string FBProfile {
            get {
                return ResourceManager.GetString("FBProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour compléter votre profil, {0}..
        /// </summary>
        public static string InfosEmpty {
            get {
                return ResourceManager.GetString("InfosEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil LinkedIn.
        /// </summary>
        public static string LinkedInProfile {
            get {
                return ResourceManager.GetString("LinkedInProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur non trouvé..
        /// </summary>
        public static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon activité communautaire.
        /// </summary>
        public static string MyComActivities {
            get {
                return ResourceManager.GetString("MyComActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes espaces commentés.
        /// </summary>
        public static string MyCommentedSpaces {
            get {
                return ResourceManager.GetString("MyCommentedSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes commentaires.
        /// </summary>
        public static string MyComments {
            get {
                return ResourceManager.GetString("MyComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité professionnelle.
        /// </summary>
        public static string MyCompany {
            get {
                return ResourceManager.GetString("MyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;a pas renseigné cette information..
        /// </summary>
        public static string MyCompanyPublic {
            get {
                return ResourceManager.GetString("MyCompanyPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiance de travail recherchée.
        /// </summary>
        public static string MyFavoritePlaces {
            get {
                return ResourceManager.GetString("MyFavoritePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon profil.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espaces ajoutés.
        /// </summary>
        public static string MySpaces {
            get {
                return ResourceManager.GetString("MySpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon site internet.
        /// </summary>
        public static string MyWebsite {
            get {
                return ResourceManager.GetString("MyWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier l&apos;adresse électronique pour les futures paiements.
        /// </summary>
        public static string PaypalEmail {
            get {
                return ResourceManager.GetString("PaypalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes informations personnelles.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes informations professionnelles.
        /// </summary>
        public static string ProfessionalInfo {
            get {
                return ResourceManager.GetString("ProfessionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil édité..
        /// </summary>
        public static string ProfilHaveBeenEdit {
            get {
                return ResourceManager.GetString("ProfilHaveBeenEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun des espaces que vous avez ajoutés n&apos;a été commenté..
        /// </summary>
        public static string RelCommentsEmpty {
            get {
                return ResourceManager.GetString("RelCommentsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorker {0} - {1:### ### ###} pts.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réseaux sociaux.
        /// </summary>
        public static string SocialNetwork {
            get {
                return ResourceManager.GetString("SocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Twitter.
        /// </summary>
        public static string TwitterProfile {
            get {
                return ResourceManager.GetString("TwitterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Viadeo.
        /// </summary>
        public static string ViadeoProfile {
            get {
                return ResourceManager.GetString("ViadeoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez attendre 48h avant de pouvoir éditer un lieu.
        /// </summary>
        public static string Wait2Days {
            get {
                return ResourceManager.GetString("Wait2Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex : fonction, entreprise, etc..
        /// </summary>
        public static string YourCompanyFunction {
            get {
                return ResourceManager.GetString("YourCompanyFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre page Facebook.
        /// </summary>
        public static string YourFacebook {
            get {
                return ResourceManager.GetString("YourFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre page LinkedIn.
        /// </summary>
        public static string YourLinkedIn {
            get {
                return ResourceManager.GetString("YourLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre pseudo twitter.
        /// </summary>
        public static string YourTwitter {
            get {
                return ResourceManager.GetString("YourTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre page Viadeo.
        /// </summary>
        public static string YourViadeo {
            get {
                return ResourceManager.GetString("YourViadeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre site internet.
        /// </summary>
        public static string YourWebsite {
            get {
                return ResourceManager.GetString("YourWebsite", resourceCulture);
            }
        }
    }
}
