//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BookingString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookingString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Email.BookingString", typeof(BookingString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom : {0}
        ///Téléphone : {1}
        ///E-mail : {2}
        ///Nom du lieu : {3}
        ///Besoin : {4}
        ///Début : {5}
        ///Fin : {6}
        ///Message : {7}.
        /// </summary>
        public static string BookingMailBody {
            get {
                return ResourceManager.GetString("BookingMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerte eWorky – Demande de réservation.
        /// </summary>
        public static string BookingMailSubject {
            get {
                return ResourceManager.GetString("BookingMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre réservation pour un(e) {0} du {1} à {2} dans l’établissement {3} ({4}) est confirmée. 
        ///Vous devrez régler la somme de {5} € directement auprès du prestataire.
        ///En espérant avoir satisfait votre demande,.
        /// </summary>
        public static string ConfirmMailBody {
            get {
                return ResourceManager.GetString("ConfirmMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky – Votre réservation est confirmée.
        /// </summary>
        public static string ConfirmMailSubject {
            get {
                return ResourceManager.GetString("ConfirmMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande de devis pour un bureau de {0} m² dans l&apos;établissement {1} ({2}) a été prise en charge par nos équipes et transmise au gérant qui vous recontactera aux coordonnées que vous nous avez indiquées dans les plus bref délais..
        /// </summary>
        public static string HandleMailBody {
            get {
                return ResourceManager.GetString("HandleMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky – Votre demande de devis a été traitée et transmise au gérant.
        /// </summary>
        public static string HandleMailSubject {
            get {
                return ResourceManager.GetString("HandleMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite à votre demande de devis pour un bureau de {0} m² dans l&apos;établissement {1} ({2}), un compte eWorky a été créé. Il vous permettra de suivre l&apos;historique de l&apos;état de vos demandes de devis et de vos réservations.&lt;br/&gt;Votre login est {3} et votre mot de passe temporaire est {4}. Vous pouvez changer votre mot de passe en cliquant sur le lien suivant {5}&lt;br /&gt;Nous vous invitons de plus à compléter votre profil en vous rendant à cette adresse : {6}.
        /// </summary>
        public static string NewMemberBody {
            get {
                return ResourceManager.GetString("NewMemberBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky – Un compte a été créé suite à votre demande de devis.
        /// </summary>
        public static string NewMemberSubject {
            get {
                return ResourceManager.GetString("NewMemberSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’ offre {0} du {1} à {2} dans l’établissement {3} ({4}) n’est pas disponible.
        ///Nous sommes donc au regret de vous annoncer que votre réservation n’a pas pu aboutir.
        ///
        ///En espérant vous revoir très vite sur eworky.com,.
        /// </summary>
        public static string RefuseMailBody {
            get {
                return ResourceManager.GetString("RefuseMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWorky – Votre réservation n’a pas pu aboutir.
        /// </summary>
        public static string RefuseMailSubject {
            get {
                return ResourceManager.GetString("RefuseMailSubject", resourceCulture);
            }
        }
    }
}
