//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.225
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worki.Resources.Email {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worki.Resources.Email.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Félicitations, vous venez d’être désigné gérant de {0} sur eWorky !
        ///
        ///Pour confirmer que vous êtes bien propriétaire ou gérant de ce lieu, 
        ///merci de cliquer sur le lien suivant : 
        ///{1}
        ///
        ///
        ///Vous pourrez ensuite vous connecter facilement à eWorky 
        ///pour modifier la fiche de {0}  : {2}
        ///
        ///avec :
        ///- votre identifiant {3}
        ///- votre mot de passe {4}.
        /// </summary>
        public static string AdminOwnership {
            get {
                return ResourceManager.GetString("AdminOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Concernant l&apos;annonce : .
        /// </summary>
        public static string Concern {
            get {
                return ResourceManager.GetString("Concern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consulter l&apos;annonce ici ==&gt;.
        /// </summary>
        public static string ConsultHere {
            get {
                return ResourceManager.GetString("ConsultHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}&lt;br /&gt;{1}&lt;br /&gt;&lt;a href=&quot;{2}&quot;&gt;Suivez-nous sur Facebook&lt;/a&gt;&lt;br /&gt;&lt;a href=&quot;{3}&quot;&gt;Suivez-nous sur twitter&lt;/a&gt;.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivez-nous sur Facebook.
        /// </summary>
        public static string FollowFacebook {
            get {
                return ResourceManager.GetString("FollowFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivez-nous sur Twitter.
        /// </summary>
        public static string FollowTwitter {
            get {
                return ResourceManager.GetString("FollowTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer à un ami.
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à De :.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour {0}.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour.
        /// </summary>
        public static string Hey {
            get {
                return ResourceManager.GetString("Hey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande d&apos;informations - {0}.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message :.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message Privé.
        /// </summary>
        public static string MP {
            get {
                return ResourceManager.GetString("MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous nous avez signalé que vous étiez gérant de {0}, bienvenue sur eWorky ! En tant que gérant de ce lieu, 
        ///- vous allez pouvoir éditer sa fiche descriptive et améliorer la qualité des informations en cliquant ici {1} ;
        ///- vous avez également la possibilité d’apposer à l&apos;entrée de votre établissement un sticker qui signale que votre espace est propice au travail et recommandé par eWorky. Ce sticker vous sera fourni gratuitement, n&apos;hésitez pas à le demander par retour d&apos;e-mail.
        ///
        ///N&apos;oubliez pas de proposer  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Ownership {
            get {
                return ResourceManager.GetString("Ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Félicitations ! Vous êtes désormais gérant de {0} !.
        /// </summary>
        public static string OwnershipSubject {
            get {
                return ResourceManager.GetString("OwnershipSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A bientôt sur eWorky,&lt;br /&gt;
        ///L’équipe eWorky&lt;br /&gt;.
        /// </summary>
        public static string SeeYouSoon {
            get {
                return ResourceManager.GetString("SeeYouSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A :.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.twitter.com/#!/eWorky_fr.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue sur eWorky !.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
